#!/usr/bin/env python3
"""Merge chapter-body translations into Localizable.xcstrings.

The catalog key for a chapter body is the ENGLISH TEXT ITSELF, exactly as
it sits in Content/Stories/<id>.json. This script reads the key straight
out of that file rather than having it retyped, so a stray character can
never break the lookup.

Add a story by appending to TRANSLATIONS:  story id → {lang → {chapter
index → translated body}}.  Partial is fine — anything absent falls back
to English at runtime, which is what ContentLanguage already expects.

Usage:  python3 translate_chapters.py
"""
from __future__ import annotations

import json
from pathlib import Path

STORIES = Path("/Users/alexandre/Magic_World/Magic World/Content/Stories")
CATALOG = Path("/Users/alexandre/Magic_World/Magic World/Localizable.xcstrings")

# story id → { lang → { chapter index → translated text } }
TRANSLATIONS: dict[str, dict[str, dict[int, str]]] = {}

# ═══════════════════════════════════════════════════════════════════════
# The Glass Heron
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["the-glass-heron"] = {
    "pt-BR": {
        0: (
            "A água subiu numa terça-feira, o que Wren achou um dia sem graça para "
            "uma coisa tão grande acontecer. Ela tinha ido dormir com o rio onde o "
            "rio devia estar, lá embaixo depois das hortas, atrás dos salgueiros, "
            "fazendo o barulho que sempre fazia. Acordou com um barulho diferente. "
            "Era mais suave e muito mais perto, e vinha da escada. De manhã a viela "
            "era um rio e o rio não fazia ideia de que estava no lugar errado. "
            "Cuidava dos seus afazeres entre as casas exatamente como cuidava dos "
            "seus afazeres entre as margens, levando um painel de cerca, um "
            "engradado de plástico e uma bota de borracha verde, tudo na mesma "
            "velocidade sem pressa. A avó já tinha levado as cadeiras para cima. "
            "Tinha feito isso no escuro, sozinha, sem acordar ninguém, e estava "
            "tomando chá no patamar quando Wren apareceu de meias. — Não desça do "
            "quinto degrau para baixo — disse a avó. — O carpete está perdido e não "
            "quero você escorregando nele. Foi tudo. Sem pânico, sem explicação. Foi "
            "assim que Wren soube que já tinha acontecido antes. Da janela do "
            "patamar dava para ver o topo dos mourões, cada um com uma golinha de "
            "espuma. O galpão dos Henderson tinha se soltado e girado sozinho para "
            "ficar virado para o lado errado, o que lhe pareceu de algum modo mais "
            "grosseiro que a própria enchente. Mais além, onde devia estar a "
            "estrada, havia uma larga lâmina de água marrom seguindo quieta na "
            "direção dos campos. A cidade tinha virado um arquipélago da noite para "
            "o dia. Cada casa era uma ilha. As pessoas dentro delas ficavam nas "
            "janelas de cima e acenavam, e depois de um tempo pararam de acenar, "
            "porque só dá para acenar por certo tempo para alguém que você não "
            "alcança. Foi aí que ela viu o pássaro. Estava na cumeeira do telhado da "
            "casa em frente, com o pescoço dobrado para dentro dos ombros do jeito "
            "que as garças fazem quando decidiram esperar. Estava muito parada. No "
            "começo ela achou que fosse uma daquelas de plástico que as pessoas põem "
            "nos lagos para assustar os peixes. Então a luz se moveu, e atravessou. "
            "Era transparente de ponta a ponta, como uma garrafa erguida contra a "
            "janela. A manhã cinzenta entrava nela por cima e saía por baixo da cor "
            "do rio, um verde-marrom suave em movimento, como se alguma coisa "
            "estivesse sendo mexida lá dentro bem devagar. Wren não chamou ninguém. "
            "Teve a sensação forte, como às vezes se tem diante de um bicho selvagem "
            "que chegou perto, de que uma criatura daquelas devia poder chegar sem "
            "alarde. Se gritasse, a avó viria, e então a avó explicaria, e então "
            "seria uma coisa que tinha sido explicada. Então ficou na janela de "
            "meias olhando, e ela não olhou para Wren nenhuma vez, e depois de vinte "
            "minutos alçou voo, e as asas quando se abriram eram a coisa mais fina "
            "que ela já tinha visto, e atravessou a água até o telhado do número "
            "onze e se dobrou de novo. A avó veio e ficou ao lado dela, em algum "
            "momento, com uma segunda xícara de chá. — Ah — disse. — Então voltou. E "
            "desceu para cuidar do carpete, o que era, pensou Wren, uma coisa "
            "extraordinária de se dizer e depois simplesmente deixar ali largada."
        ),
        1: (
            "No segundo dia a gritaria tinha parado. Tinha sido divertido no primeiro "
            "dia, de um jeito sombrio. O senhor Adeyemi do número nove tinha uma voz "
            "que alcançava longe e gritava as notícias por cima da água como um "
            "pregoeiro: a luz tinha caído na parte de baixo, a venda tinha subido o "
            "estoque para a prateleira de cima, alguém tinha visto um lúcio passando "
            "nadando pela caixa de correio. As pessoas se debruçavam e riam. Mas "
            "gritar o dia inteiro deixa a pessoa rouca, e deixa cansada, e na tarde "
            "de quarta as janelas tinham silenciado e cada um estava sozinho na sua "
            "casa sendo sensato. Wren escreveu um bilhete. Fez isso mais para ter "
            "alguma coisa a fazer. Arrancou uma folha do fim do caderno e escreveu "
            "*vocês estão bem aí*, e não pôs nome nenhum porque não sabia para qual "
            "casa estava escrevendo. Dobrou bem pequeno e pôs no parapeito de fora "
            "debaixo de uma pedra. Fez do jeito que se joga uma moeda num poço. Sem "
            "esperar nada de verdade. Só fazendo. De manhã tinha sumido. No lugar "
            "havia um papel diferente, úmido numa ponta, dobrado do mesmo jeito. "
            "Dizia: *sim, e temos pão demais.* Wren ficou na janela com ele nas duas "
            "mãos por um tempo longo. Depois disso, ninguém precisou explicar nada a "
            "ninguém. Essa foi a parte estranha, a parte em que ela pensou durante "
            "anos depois — como uma coisa vira normal depressa quando é útil. Na "
            "quinta havia bilhetes em quatro parapeitos. Na sexta havia bilhetes em "
            "doze. A garça ia de telhado em telhado com seu passo longo e cuidadoso, "
            "e nunca tinha pressa, e nunca ia a uma casa que não tivesse posto "
            "alguma coisa para fora. Onde os pés dela tocavam a água na beira de um "
            "telhado, a água tinia, bem de leve, como uma taça batida com a colher. "
            "Se você estivesse prestando atenção, dava para saber em que parte da "
            "cidade ela estava. Os bilhetes não eram dramáticos. Era disso que Wren "
            "gostava neles. *Temos pão demais. A senhora Pryor está com tosse e sem "
            "mel. Alguém consegue chegar nos Kelly, ninguém viu luz na casa dos "
            "Kelly. Tem mel no número quatro, avisem a senhora Pryor. Os Kelly foram "
            "para a casa da filha no domingo, estão bem, parem de se preocupar com "
            "os Kelly.* E mais tarde, quando já durava cinco dias e todo mundo "
            "estava entediado e com medo em igual medida: *Tomas faz oito anos hoje "
            "e não tem bolo.* Uma dúzia de casas pôs alguma coisa no parapeito "
            "naquela noite. Wren viu a garça atravessar a água nove vezes antes de "
            "escurecer, indo mais devagar a cada vez, e uma vez chegou tão perto da "
            "janela dela que dava para ver o rio revolvendo dentro do peito. De "
            "manhã Tomas do número seis tinha uma coroa de papel, uma barra de "
            "chocolate, um desenho de cachorro assinado por alguém chamada Iris, um "
            "livro sobre submarinos com a primeira página arrancada, e quatro "
            "bilhetes separados que diziam *feliz aniversário* em quatro letras "
            "diferentes. A avó assistiu a tudo isso da cadeira do patamar sem muito "
            "comentário. — Ela não quer nada? — perguntou Wren. — Por fazer isso? A "
            "avó pensou naquilo com a seriedade que a pergunta merecia. — Alguns que "
            "ajudam — disse — não gostam que agradeçam. Não é grosseria. É só que "
            "agradecer transforma aquilo num favor, e nunca foi um favor. Sempre foi "
            "só a coisa que precisava ser feita."
        ),
        2: (
            "Na sexta noite a garça não veio. Wren pôs o bilhete no horário de "
            "sempre, debaixo da pedra de sempre, e ficou olhando o parapeito do "
            "patamar até a avó mandar ela dormir, e de manhã o bilhete ainda estava "
            "lá. Úmido, e enrolando na ponta, e por ler. No começo achou que tinha "
            "feito alguma coisa errada. Releu o próprio bilhete quatro vezes "
            "procurando o erro nele. Dizia: *a tosse da senhora Pryor piorou, alguém "
            "tem termômetro.* Pôs de novo na manhã seguinte com uma pedra em cima e "
            "foi à janela a cada vinte minutos. Às onze horas os parapeitos ao longo "
            "da viela tinham começado a encher. Dava para vê-los do patamar: "
            "quadrados brancos aparecendo no número quatro, no número nove, na casa "
            "dos Henderson, no número onze. Todo mundo tinha escrito alguma coisa. "
            "Todo mundo estava esperando. Não veio nada. É difícil descrever como "
            "foi aquele dia sem fazer parecer pior do que foi. Ninguém estava em "
            "perigo. A água não tinha subido; havia comida em todas as casas; a luz "
            "estava ligada na parte de cima da viela e as pessoas carregavam os "
            "telefones na casa dos Adeyemi passando por cima num gancho de "
            "varal. Nada tinha mudado de fato, exceto que treze bilhetes estavam "
            "sentados em catorze parapeitos molhando, e todo mundo podia ver o "
            "bilhete de todo mundo não sendo recolhido. A cidade tinha se "
            "acostumado em cinco dias. Era isso. Cinco dias não é nada — é menos que "
            "uma semana de aula — e tinha bastado para um modo inteiro de viver se "
            "estabelecer e começar a parecer permanente. A avó de Wren fez o almoço "
            "e não mencionou os bilhetes. Às quatro da tarde o senhor Adeyemi gritou "
            "por cima da água. Foi a primeira gritaria em três dias e soou "
            "enferrujada e alta demais, e ele perguntou se alguém tinha termômetro, "
            "e alguém do número quatro gritou de volta que tinha, e seguiu-se um "
            "negócio lento, difícil, de quarenta minutos, envolvendo um balde, um "
            "pedaço de corda de varal e um bocado de instrução sendo gritada de três "
            "direções ao mesmo tempo. O termômetro chegou seco na casa da senhora "
            "Pryor. A coisa toda tinha levado quarenta minutos e doze pessoas, e "
            "tinha funcionado, e Wren ficou na janela do patamar vendo o balde "
            "voltar pela água marrom na corda e entendeu uma coisa para a qual não "
            "teve palavras senão muito depois. A garça não estava fazendo uma coisa "
            "que eles não podiam fazer. Estava fazendo uma coisa que eles tinham "
            "parado de fazer. Ela disse isso à avó, mais ou menos, com palavras "
            "piores, durante o chá. A avó ouviu até o fim sem interromper, como "
            "sempre fazia, e depois disse: — Ela veio no ano em que eu tinha nove "
            "anos também. Quatro dias, daquela vez. E quando parou de vir, a viela "
            "esticou uma corda do portão dos Henderson até o nosso e deixou lá por "
            "seis anos. — Mexeu o chá. — Ainda estava lá quando sua mãe nasceu. "
            "Alguém tirou no fim porque tinha ficado verde. — Por que parou? — "
            "Tenho sessenta anos de pensar nisso e só tenho uma resposta, e você não "
            "vai gostar. Wren esperou. — Porque estávamos nos virando — disse a "
            "avó. A garça voltou na oitava noite. Wren viu do patamar por volta das "
            "seis da manhã, seguindo pela linha dos telhados das casas de número "
            "ímpar na luz cinzenta, sem pressa, exatamente como antes, recolhendo "
            "seis bilhetes molhados que a essa altura diziam coisas como *a corda "
            "funcionou, usem a corda* e *a senhora Pryor melhorou* e, do número "
            "seis, em letra de criança, *onde você foi.* Levou todos. Não trouxe "
            "nada de volta naquela manhã, até onde alguém pôde perceber. E a corda "
            "continuou esticada entre os portões, porque a essa altura as pessoas "
            "já tinham se acostumado com aquilo também."
        ),
        3: (
            "O rio foi embora do jeito que tinha vindo — sem pedir desculpa, ao longo "
            "de quatro dias lentos. Primeiro voltaram os mourões, depois o topo dos "
            "portões, depois os portões. A viela reapareceu debaixo de uma camada de "
            "lodo da cor de chá com leite, e cheirava a moeda fria e a alguma coisa "
            "mais velha por baixo. Havia um peixe no jardim dos Henderson e ninguém "
            "conseguia concordar sobre o que fazer com ele. Wren subiu ao patamar na "
            "última manhã, antes da escola, naquela parte cinzenta do dia em que "
            "tudo parece inacabado. A garça ainda estava lá. Mas tinha deixado de "
            "ser transparente. Estava na cumeeira do telhado em frente exatamente no "
            "lugar em que tinha estado na primeira manhã, e a luz não atravessava "
            "mais. Estava verde nas bordas e turva no meio, do jeito que o vidro "
            "fica quando o mar terminou com ele. Não havia nada se movendo dentro do "
            "peito dela. Ela atravessou a viela de bota por quinze centímetros de "
            "lodo e pegou a escada no galpão dos Henderson, que continuava virado "
            "para o lado errado, e subiu, o que não devia ter feito, e pôs a mão "
            "nela. Estava fria, e era mais pesada do que parecia, e não se mexeu. "
            "Desceu carregando debaixo de um braço com a escada balançando e pôs no "
            "mourão de canto no fim da viela, onde a luz vem pela estrada no fim da "
            "tarde. Ainda está lá. Alguém pôs uma laje de pedra embaixo com o tempo "
            "para não afundar quando o chão amolecesse. Quem passa acha que é um "
            "enfeite, e é, agora, mas também é uma garça. Os bilhetes foram para uma "
            "lata de biscoito debaixo da cama de Wren. Eram trinta e um, de doze "
            "casas diferentes, incluindo um que dizia *tem mel no número quatro* e "
            "um que só dizia *sim*. A avó disse que deviam guardar a lata em algum "
            "lugar sensato. Guardaram debaixo da cama."
        ),
    },
}

# ═══════════════════════════════════════════════════════════════════════
# Where the Moths Sleep
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["where-the-moths-sleep"] = {
    "pt-BR": {
        0: (
            "A luz do sótão estava acesa desde que qualquer um conseguia lembrar, e "
            "ninguém sabia dizer quem tinha acendido. Incomodava Ines mais do que "
            "incomodava qualquer outra pessoa. Ela tinha perguntado ao tio duas "
            "vezes. Na primeira ele tinha dito que era mais barato do que discutir "
            "sobre isso, o que não era uma resposta. Na segunda tinha dito que "
            "algumas coisas numa casa são mais velhas que as pessoas dentro dela, o "
            "que era menos resposta ainda que a primeira mas soava mais como uma. "
            "Dava para ver de noite do jardim — uma linha laranja fina em volta da "
            "borda do alçapão, pendurada no escuro do teto do patamar como o desenho "
            "de uma porta em vez de uma porta. Ela subiu na primeira noite quente do "
            "ano, porque o alçapão tinha começado a zumbir. Isso era novo. Era um "
            "som grave, não elétrico, mais parecido com o barulho que uma abelha faz "
            "dentro de um pote de geleia a três cômodos de distância. Tinha começado "
            "na terça e na sexta ela já sentia nos degraus da escada. Esperou o tio "
            "sair para trancar a estufa, e então subiu. O sótão estava cheio de "
            "mariposas. Não esvoaçando. Não se atirando feito bobas contra a "
            "lâmpada, que é o que mariposas fazem e a única coisa que Ines já tinha "
            "visto uma fazer. Estas estavam descansando. Centenas delas, dobradas "
            "rentes às vigas e à parte de baixo das telhas, asas fechadas, "
            "absolutamente imóveis, arranjadas do jeito que as páginas se arranjam "
            "num livro. Eram da cor de papel velho — algumas quase brancas, algumas "
            "do amarelo de uma página que ficou na janela, umas poucas quase "
            "marrons. Não se assustaram quando a cabeça dela apareceu pelo alçapão. "
            "Uma perto da mão dela se ajeitou muito de leve, do jeito que uma pessoa "
            "se remexe na cadeira. Ela sentou na beira do alçapão com as pernas para "
            "dentro, porque o assoalho não parecia confiável, e olhou para a mais "
            "próxima. Havia alguma coisa nas asas. Não um padrão. Ela sabia como são "
            "os padrões de mariposa: olhos e pintas e as carinhas falsas. Aquilo era "
            "um quadro. Um bem pequeno, pintado do jeito que um selo é impresso, "
            "atravessando as duas asas de modo que a emenda passava pelo meio dele. "
            "Era uma cozinha. Uma cozinha amarela com uma janela sobre a pia e uma "
            "cadeira puxada para fora da mesa. Olhou para a seguinte. Um barco, num "
            "mar cinzento, visto por trás. Olhou para a seguinte, e era um rosto que "
            "ela quase conhecia, e depois não, e o quase ficou com ela pela escada "
            "inteira até embaixo."
        ),
        1: (
            "Ela subiu de novo na noite seguinte, e na noite depois dessa. Na quarta "
            "noite já tinha descoberto como pegar uma. Você não pega uma mariposa; "
            "você encosta o dedo na parede ao lado dela e espera, e mais cedo ou "
            "mais tarde ela caminha para cima de você, sem pressa, como alguém "
            "subindo num ônibus. A que subiu no dedo dela na quarta noite tinha um "
            "corredor pintado nas asas. Um corredor comprido com uma passadeira, e "
            "no fim dele, uma porta verde. Ela segurou sob a lâmpada e olhou por um "
            "tempo longo. Quanto mais olhava, mais certeza tinha de que já tinha "
            "andado por aquele corredor. Sabia como era a luz na outra ponta à "
            "tarde. Sabia que a passadeira tinha uma parte gasta a dois terços do "
            "caminho e que dava para sentir através da meia. E exatamente ao mesmo "
            "tempo, com exatamente a mesma certeza, sabia que nunca tinha estado ali "
            "na vida. O tio subiu a escada atrás dela com duas canecas de chá, o que "
            "é uma coisa difícil de fazer e sugeria prática. Ele não pareceu "
            "surpreso com nada daquilo. Passou uma caneca para ela, sentou num "
            "engradado virado que claramente já tinha servido de assento muitas "
            "vezes, e olhou para a mariposa no dedo dela. — Porta verde — disse. — "
            "Essa é boa. Alguém sente falta dessa. Ines não disse nada, porque não "
            "conseguia pensar numa pergunta pequena o bastante para começar. — As "
            "pessoas deixam cair sonhos — disse o tio. — O tempo todo. Do jeito que "
            "se deixa cair uma luva do bolso: você não sente ir, só descobre depois "
            "que ficou só com uma. Acordar rápido demais, alguém falar seu nome, o "
            "despertador tocar na parte errada. E o sonho cai. — Bebeu um pouco de "
            "chá. — Eles têm que ir para algum lugar. Tudo tem que ir para algum "
            "lugar. Esta casa está recolhendo eles desde antes de ser minha, e antes "
            "de ser da minha mãe, e eu nunca entendi por que esta casa e não a do "
            "lado. — Quantas são? — Parei de contar lá por mil novecentos e noventa. "
            "Ines girou a mão devagar para a mariposa ficar nivelada. Na parede "
            "acima dela, cem asas pálidas seguravam cem quadros pequenos: uma "
            "bicicleta, um corredor de hospital, uma encosta com um muro "
            "atravessado, um casamento, um cachorro, uma loja que ela tinha quase "
            "certeza de ser a loja da Rua da Ponte mas com outras janelas. — Elas "
            "podem voltar? — disse. — Dá para devolver uma para alguém? O tio olhou "
            "para o chá um tempo. — Essa — disse — é a parte difícil."
        ),
        2: (
            "A que ela queria era o rosto. Tinha achado na primeira noite — terceira "
            "ao longo da viga, perto da chaminé — e tinha voltado a ela toda noite "
            "desde então, e toda noite acontecia a mesma coisa. Ela olhava e pensava "
            "*ah, esse é o* — e aí o nome não chegava. Era um homem. De meia-idade, "
            "ou chegando lá. Cabelo escuro recuando na frente. Estava olhando um "
            "pouco à esquerda de quem quer que o estivesse sonhando, e estava no "
            "meio de dizer alguma coisa, e as sobrancelhas estavam erguidas. Estava "
            "pintado melhor que as outras. Essa era a parte estranha. A cozinha e o "
            "barco e a porta verde estavam todos pintados do jeito que uma coisa é "
            "pintada de memória — as partes importantes nítidas, o resto vago. Esse "
            "tinha uma gola de camisa com um botão faltando na ponta, e uma "
            "cicatriz pequena atravessando uma sobrancelha, e aquele tipo de detalhe "
            "que só se consegue quando alguém olhou para um rosto durante anos e "
            "anos e anos. Ela perguntou ao tio quem era. Ele subiu e olhou um tempo "
            "com as mãos nos bolsos e disse que não fazia ideia, e que ele mesmo "
            "vinha se perguntando sobre aquela desde mais ou menos 2003. Ela fez a "
            "coisa sensata, o que levou três semanas. Desenhou — mal, depois menos "
            "mal, depois na quarta tentativa bem o bastante para ser reconhecível — "
            "e carregou o desenho pela cidade no bolso do casaco e mostrou para as "
            "pessoas. A mulher da padaria disse não. O homem da loja de bicicleta "
            "disse não, e depois segurou o desenho com o braço esticado e disse não "
            "de novo, mais devagar. O bibliotecário disse que ele parecia o irmão de "
            "alguém, o que não era útil. O padre Costa disse que ele parecia o irmão "
            "de todo mundo, o que era menos útil ainda. Um homem no ponto de ônibus "
            "disse que era um desenho muito bom, o que ela agradeceu mas não pôde "
            "usar para nada. No fim de três semanas tinha mostrado para trinta e uma "
            "pessoas e nenhuma delas o conhecia. Sentou no muro em frente à farmácia "
            "com o desenho no joelho e chegou à conclusão, e não gostou de chegar à "
            "conclusão. Só havia dois jeitos de aquilo terminar. Ou a pessoa que "
            "tinha deixado cair aquele sonho tinha se mudado — caso em que a "
            "mariposa ficaria naquela viga até a casa cair. Ou a pessoa que tinha "
            "deixado cair estava morta, e o sonho tinha se soltado do jeito que o "
            "último de qualquer coisa se solta, e tinha subido a ladeira e entrado "
            "por baixo das telhas e se dobrado contra uma viga, e não havia mais "
            "ninguém no mundo a quem pudesse ser entregue. Ela foi para casa e subiu "
            "a escada e sentou na beira do alçapão por um tempo longo. O tio subiu "
            "em algum momento com o chá. Não perguntou como tinha sido; tinha "
            "claramente deduzido como tinha sido pelo fato de ela estar sentada no "
            "escuro. — Tem umas quatrocentas assim — disse. — Que eu saiba. As que "
            "ninguém reclama. Não vão a lugar nenhum. Não morrem, até onde consigo "
            "ver: tenho uma lá em cima com uma carroça e não passa carroça nesta "
            "ladeira desde antes da guerra. — Então para que servem? — Elas não "
            "*servem* para nada — disse. — Essa é a parte que mais demorei a "
            "entender. Passei uns quinze anos tentando fazer este lugar ser útil e "
            "não cheguei a lugar nenhum, porque estava fazendo a pergunta errada. — "
            "Apontou com a cabeça para as vigas. — Não é um achados e perdidos. "
            "Ninguém vem ao balcão. É só onde elas param. Ines olhou para o homem de "
            "sobrancelhas erguidas, no meio de dizer alguma coisa, para alguém que o "
            "tinha amado o bastante para guardar o botão faltando. — Isso é triste "
            "— disse. — É — concordou o tio. — Mas olha o estado dele. Alguém "
            "gostava muitíssimo daquele homem. Isso continua verdade. É verdade "
            "agora, naquela viga, venha alguém buscar ou não. — Bebeu o chá. — Há "
            "coisas piores para se ter uma casa cheia."
        ),
        3: (
            "Levou quase o verão inteiro para descobrir, e descobrir não teve nada de "
            "mágico. Foi na maior parte fazer perguntas constrangedoras às pessoas e "
            "errar. As regras, até onde Ines chegou a estabelecer, eram estas. Uma "
            "mariposa não ia com qualquer um. Você podia levar uma nas mãos em "
            "concha até uma pessoa e abrir as mãos e ela ficava ali feito um pedaço "
            "de papel, completamente desinteressada, e mais cedo ou mais tarde "
            "voltava andando pela sua manga. Tinha que ser no lusco-fusco. Não "
            "escuro, não noite — lusco-fusco, os vinte minutos em que os postes já "
            "estão acesos mas você ainda enxerga a cor das coisas. E você tinha que "
            "estar perto de onde a pessoa estava quando perdeu. Essa era a parte que "
            "tornava difícil, porque significava descobrir quem, o que significava "
            "perguntar, e não há jeito bom de perguntar a um adulto se ele "
            "recentemente extraviou um sonho sobre um barco. Ela deu um jeito "
            "perguntando sobre os quadros. A mulher da padaria, quando Ines "
            "descreveu um mar cinzento visto da popa de um barco, parou de contar o "
            "troco e disse: — Meu pai tinha um barco assim — e depois: — Por quê? — "
            "e Ines disse que tinha visto uma pintura, o que era mentira, mas só uma "
            "pequena. Ela soltou a mariposa do barco em frente à padaria no "
            "lusco-fusco de uma quinta-feira. Entrou pela janela de cima, que estava "
            "aberta por causa do calor, e não saiu. O homem que consertava bicicleta "
            "tinha perdido o corredor com a porta verde. Ela tinha quase certeza "
            "antes de perguntar e certeza completa depois, pelo jeito como ele disse "
            "\"essa era a casa da minha avó\" e então parou de falar e voltou a "
            "centrar a roda que estava centrando. Ela soltou em frente à loja dele "
            "na noite seguinte. Ele ainda estava lá, trabalhando até tarde, e não a "
            "viu fazer. Ela assistiu do outro lado da rua a mariposa entrar por "
            "baixo da porta de enrolar. Ele saiu mais ou menos um minuto depois e "
            "ficou na calçada, olhando para nada em particular, por um bom tempo. "
            "Depois entrou de novo e voltou para a roda. Ele nunca comentou com ela, "
            "e ela nunca comentou com ele, e por mais ou menos um ano depois disso "
            "ele fez os cabos de freio dela de graça e nenhum dos dois jamais disse "
            "por quê. Ela fez dezenove naquele verão. Dezenove de centenas, e levou "
            "de junho até meados de setembro, e errou quatro e teve que trazer de "
            "volta. No fim subiu a escada uma última noite antes das aulas "
            "começarem, esperando — não sabia bem o quê. Alguma falha visível. "
            "Algum vão nas vigas onde dezenove costumavam estar. O sótão estava "
            "exatamente igual. — Sempre está — disse o tio, do engradado. — Isso não "
            "é motivo para não fazer. E ele deixou a luz acesa, do jeito que sempre "
            "tinha sido deixada acesa, e desceram e fecharam o alçapão, e o zumbido "
            "seguiu bem baixinho acima deles a noite toda, do jeito que seguia havia "
            "anos, do jeito que presumivelmente ainda segue."
        ),
    },
}

# ═══════════════════════════════════════════════════════════════════════
# The Cat Who Walks You Home
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["the-cat-who-walks-you-home"] = {
    "pt-BR": {
        0: (
            "O poste em frente ao número quarenta estava apagado desde fevereiro e a "
            "prefeitura tinha um número de protocolo para ele. Bruno sabia o número "
            "de protocolo de cor porque a mãe tinha dito ao telefone treze vezes, e "
            "a cada vez tinha dito um pouco mais devagar, e a cada vez uma pessoa "
            "diferente tinha dito a ela que estava registrado. O que o número de "
            "protocolo significava, na prática, era que os últimos sessenta metros "
            "da Rua da Cordoaria eram escuros. Não era assustador em outubro. Em "
            "outubro você descia do ônibus às quatro e meia e a luz ainda estava "
            "indo embora. No fim de novembro já era escuro de verdade às cinco e os "
            "sessenta metros tinham virado uma coisa em que Bruno pensava no ônibus, "
            "a partir de umas três paradas antes. Não havia nada ali. Ele sabia "
            "disso. Sabia do jeito que se sabem as coisas que não fazem a menor "
            "diferença: havia um muro de um lado, e os fundos do depósito de "
            "azulejos do outro, e um vão de porta, e a esquina. Não havia ninguém "
            "ali. Nunca tinha acontecido nada ali. Era só escuro, e escuro em que "
            "você entra sozinho aos onze anos é uma substância específica, mais "
            "pesada que a outra. Ele tinha chegado a várias conclusões sobre aquilo "
            "no fim de novembro. A primeira era que correr piorava. Tinha tentado "
            "correr na primeira semana e tinha chegado à esquina com o coração "
            "disparado e a mochila batendo no quadril e a sensação muito forte de "
            "ter confirmado alguma coisa. Andar era melhor. Andar era uma "
            "declaração. A segunda era que o vão de porta era a parte difícil. "
            "Ficava recuado uns um metro da calçada, e era o único lugar nos "
            "sessenta metros inteiros onde podia haver alguma coisa que você não "
            "veria até estar na altura. Ele tinha desenvolvido, sem nunca ter "
            "decidido, o hábito de andar pelo outro lado da rua e virar a cabeça "
            "para lá no último instante. Levava meio segundo. Fez isso toda "
            "santa noite durante quatro meses. A terceira coisa era que nada daquilo "
            "era razoável, e ele sabia que não era razoável, e saber não fazia a "
            "menor diferença. Ele gostaria que isso constasse. Não era uma criança "
            "pequena. Tinha passado por aquele vão de porta à luz do dia umas "
            "quatrocentas vezes sem pensar nada. O saber ficava num lugar e o andar "
            "acontecia em outro, e os dois não conversavam. Ele viu o gato pela "
            "primeira vez numa quinta-feira no começo de dezembro. Tinha feito a "
            "curva perto da farmácia e parado, do jeito que tinha começado a parar, "
            "para o pequeno assunto particular de decidir andar. E lá, na outra "
            "ponta, bem na esquina onde a luz voltava, alguma coisa estava sentada. "
            "Era cinza e era comum e estava virada para ele. Ele andou. Ela ficou. "
            "Chegou mais ou menos no meio e ela levantou, sem pressa, e virou, e "
            "andou dobrando a esquina à frente dele — não indo embora, exatamente, "
            "mais no passo de quem presume que você vem junto — e quando ele dobrou "
            "a esquina para a luz ela estava sentada de novo, dez metros adiante, "
            "esperando. Ele disse: — Oi. Ela olhou para ele. Ele estendeu a mão, do "
            "jeito que se faz, e fez o barulho, e ela levantou e foi embora rente ao "
            "muro e sumiu entre dois carros estacionados."
        ),
        1: (
            "Ele comentou na escola e descobriu, ao longo de mais ou menos uma "
            "semana, que aquilo não era um fenômeno novo e que cada um tinha uma "
            "versão ligeiramente diferente. Inês tinha um na escadaria atrás do "
            "mercado. O dela era preto e ela chamava de Senhor e tinha subido a "
            "escadaria com ela toda noite em janeiro, quando o pai estava "
            "trabalhando até tarde. Teodoro disse que o dele era laranja e morava "
            "perto do campo de futebol e só aparecia quando chovia, sobre o que ele "
            "tinha uma teoria. As gêmeas do ano acima disseram que nunca tinham "
            "visto gato nenhum mas que a mãe delas tinha visto, quando era pequena, "
            "na estrada que vai para a pedreira, e que na versão dela ele tinha "
            "saído de debaixo de um carro e ido com ela o caminho todo até o "
            "entroncamento e não estava mais lá quando ela se virou. A única regra "
            "que estava em todas as versões, e Bruno conferiu, era esta: ele nunca "
            "vinha quando você chamava. Ele juntou doze relatos até o fim de janeiro "
            "e escreveu no fim do caderno de português, sob um título que depois "
            "rabiscou porque parecia infantil. Cinza, preto, laranja, rajado, e um "
            "sobre o qual Rita não abria mão: branco, com o rosto cinza. Ruas "
            "diferentes. Anos diferentes. O da mãe das gêmeas era de mais ou menos "
            "1994, o que fazia dele ou um gato muito velho ou, como Teodoro "
            "observou em considerável volume no corredor, não um gato. Ninguém tinha "
            "tocado num. Ele conferiu isso especificamente, porque tinha estendido a "
            "mão na primeira noite e tinha se sentido bobo por uma semana depois. "
            "Ninguém tinha. Eles chegavam a uns dois metros e ficavam a dois metros "
            "e sumiam assim que você estava na luz. Ninguém tinha visto um chegar, "
            "tampouco. Isso ele demorou mais a notar, porque é uma coisa difícil de "
            "notar, a ausência. Em todos os doze relatos o gato simplesmente já "
            "estava lá, sentado, na outra ponta, virado para você. Não vindo andando. "
            "Não saindo de debaixo de nada. Sentado, no lugar onde o escuro "
            "terminava, já olhando para você antes de você olhar para ele. Você "
            "podia ficar no alto da rua às oito da noite quando estava perfeitamente "
            "bem e dizer *psiu, psiu, psiu* até se sentir bobo, e não acontecia "
            "nada. Teodoro tinha tentado com comida. Inês tinha tentado uma semana "
            "seguida em fevereiro por pura curiosidade científica e não ganhou nada "
            "além de um resfriado. E então numa noite em que você estava com medo, "
            "ele estava lá. A avó de Bruno, que foi a única adulta a quem ele "
            "contou, ouviu tudo até o fim com as mãos na pia e depois disse uma "
            "coisa que ele não entendeu por uns quatro anos. Disse: — Não é o gato "
            "que muda. Ele perguntou o que aquilo deveria significar. Ela secou um "
            "copo e pôs no escorredor e não respondeu por tempo suficiente para ele "
            "supor que não ia responder. — Quando eu era menina — disse —, havia uma "
            "mulher nesta rua que não conseguia sair depois de escurecer de jeito "
            "nenhum. Não que não quisesse: não conseguia. Alguma coisa tinha "
            "acontecido com ela, antes, em outro lugar, e ninguém na rua nunca soube "
            "o quê, e não era da nossa conta. E por uns vinte anos, sempre que ela "
            "precisava ir a algum lugar de noite, um dos homens calhava de estar no "
            "alto da escadaria fumando um cigarro. Homens diferentes. Nunca o mesmo "
            "duas vezes seguidas. Nunca combinado, até onde eu pude perceber. — Não "
            "é a mesma coisa. — Não — concordou a avó. — Não é. E deu o pano a ele "
            "para secar, que era como as conversas terminavam naquela cozinha."
        ),
        2: (
            "Em março os dias ficaram mais longos e os sessenta metros voltaram a ser "
            "sessenta metros. Bruno notou isso só do jeito que se nota que um dente "
            "parou de doer, ou seja, tarde, e por acidente. Estava subindo do ônibus "
            "numa terça e estava pensando numa coisa que tinha acontecido na aula de "
            "matemática, e fez a curva perto da farmácia e não parou. Estava quase no "
            "fim quando percebeu que não tinha olhado para a esquina. Parou então, no "
            "meio da parte escura, e se virou, e olhou direito para onde tinha vindo "
            "e para onde estava indo, e não havia nada em nenhuma das direções. O "
            "depósito de azulejos. O muro. O vão de porta. As lixeiras. O gato não "
            "estava lá. Ficou ali um tempo, e sentiu — e ele nunca conseguiu fazer "
            "isso soar sensato — um pouco rejeitado. Voltou na noite seguinte de "
            "propósito. Desceu pelo meio da rua devagar, olhando cada parte dela por "
            "vez: o muro, os fundos do depósito, as lixeiras, o vão de porta. Ficou "
            "dentro do vão de porta por um minuto inteiro, o que ele nunca tinha "
            "feito na vida, e descobriu que era um vão de porta com um degrau gasto "
            "e umas folhas no canto e um ferrolho pintado por cima umas nove vezes. "
            "Disse *psiu*, duas vezes, baixinho, se sentindo ridículo. Havia um carro "
            "em algum lugar lá na avenida, e a televisão de alguém através de uma "
            "janela, e esse era o conteúdo inteiro da Rua da Cordoaria às seis e dez "
            "de uma quarta-feira de março. Tentou de novo em abril, com um pedaço de "
            "chouriço, do que ele ainda tem vergonha. Disse, para a rua vazia: — Eu "
            "ainda estou aqui, sabia. Não aconteceu nada, que é o que acontece. Foi "
            "para casa e jantou e não comentou, e levou até mais ou menos abril para "
            "entender que o gato não tinha parado de vir. Ele tinha parado de "
            "precisar. Eram dois acontecimentos completamente diferentes que tinham "
            "parecido, de dentro, o mesmo."
        ),
        3: (
            "No inverno seguinte a luz em frente ao número quarenta continuava "
            "apagada e havia um número de protocolo novo. Bruno tinha doze anos a "
            "essa altura e tinha parado de pensar nos sessenta metros por completo, e "
            "a razão de ele lembrar qualquer coisa disso é uma menina chamada Cátia "
            "que se mudou para os apartamentos acima da farmácia em outubro e que "
            "tinha nove anos. Ele reparou nela porque ela parou. Fez a curva uma "
            "noite por volta das cinco e meia e havia uma pessoa pequena parada no "
            "alto da parte escura com a mochila apertada contra o peito nos dois "
            "braços, fazendo o assunto particular de decidir, e não decidindo. Ele "
            "sabia exatamente o que ela estava fazendo. Tinha feito por quatro meses. "
            "Não disse nada sobre isso, porque tinha doze anos e sabia que seria a "
            "coisa errada. Passou por ela e disse \"boa noite\" e seguiu em "
            "velocidade normal, e ela veio atrás dele, uns quatro metros atrás, o "
            "caminho todo até dobrar a esquina para a luz. Ela fez isso toda noite "
            "por umas três semanas, a quatro metros, e nenhum dos dois jamais "
            "mencionou. E então numa noite no começo de dezembro ele estava "
            "atrasado — tinha ficado para o futebol e pegado o ônibus mais tarde — e "
            "fez a curva quase às sete, e a parte escura estava escura de verdade, e "
            "não havia ninguém nela. E na outra ponta, na esquina onde a luz voltava, "
            "alguma coisa cinza estava sentada virada para ele. Bruno parou. Ficou "
            "ali no alto da Rua da Cordoaria por um tempo, bem mais do que precisava, "
            "olhando sessenta metros de escuro abaixo para um gato que não via havia "
            "um ano e meio. Então andou. Ele levantou quando Bruno estava na metade, "
            "sem pressa, e dobrou a esquina à frente dele no passo de quem presume "
            "que você vem junto, e quando ele entrou na luz estava sentado dez metros "
            "adiante. Ele não estendeu a mão dessa vez. Tinha aprendido isso pelo "
            "menos. Disse: — Eu sei. Estou indo. E ele olhou para Bruno, e levantou, "
            "e foi embora rente ao muro e sumiu entre dois carros estacionados. Ele "
            "contou à avó naquela noite, porque ela continuava sendo a única adulta a "
            "quem ele contava, e ela estava fazendo a mesma coisa na mesma pia. — Ele "
            "voltou — disse. — Eu tenho doze anos. — Hum — disse a avó. — Mas eu não "
            "estava com medo. Eu estava atrasado, só isso. Eu só estava atrasado. A "
            "avó fechou a torneira e secou as mãos e olhou para ele por um instante "
            "com uma expressão que ele não conseguiu ler de jeito nenhum. — Bruno — "
            "disse. — Você estava sozinho, no escuro, e você tem doze anos, e você "
            "ficou parado no alto daquela rua por um minuto inteiro antes de se "
            "mexer. Eu vi da janela. — Pendurou o pano no varão. — Não é o gato que "
            "muda."
        ),
    },
}


# ═══════════════════════════════════════════════════════════════════════

def main() -> None:
    catalog = json.loads(CATALOG.read_text())
    strings = catalog["strings"]
    added = 0

    for story_id, by_lang in TRANSLATIONS.items():
        story = json.loads((STORIES / f"{story_id}.json").read_text())
        chapters = {c["index"]: c["text"] for c in story["chapters"]}

        # Collect per-chapter so one entry can carry several languages.
        per_chapter: dict[int, dict[str, str]] = {}
        for lang, by_index in by_lang.items():
            for idx, text in by_index.items():
                per_chapter.setdefault(idx, {})[lang] = text

        for idx, langs in sorted(per_chapter.items()):
            key = chapters.get(idx)
            if key is None:
                print(f"  !! {story_id} has no chapter {idx}")
                continue

            entry = strings.get(key, {"extractionState": "manual",
                                      "localizations": {}})
            locs = entry.setdefault("localizations", {})
            locs["en"] = {"stringUnit": {"state": "translated", "value": key}}
            for lang, value in langs.items():
                locs[lang] = {"stringUnit": {"state": "translated",
                                             "value": value}}
            strings[key] = entry
            added += 1
            print(f"  {story_id} ch{idx}: {', '.join(sorted(langs))}")

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False))
    print(f"\n{added} chapter bodies merged; catalog now {len(strings)} keys")


if __name__ == "__main__":
    main()
