#!/usr/bin/env python3
"""Merge chapter-body translations into Localizable.xcstrings.

The catalog key for a chapter body is the ENGLISH TEXT ITSELF, exactly as
it sits in Content/Stories/<id>.json. This script reads the key straight
out of that file rather than having it retyped, so a stray character can
never break the lookup.

Add a story by appending to TRANSLATIONS:  story id → {lang → {chapter
index → translated body}}.  Partial is fine — anything absent falls back
to English at runtime, which is what ContentLanguage already expects.

Usage:  python3 translate_chapters.py
"""
from __future__ import annotations

import json
from pathlib import Path

STORIES = Path("/Users/alexandre/Magic_World/Magic World/Content/Stories")
CATALOG = Path("/Users/alexandre/Magic_World/Magic World/Localizable.xcstrings")

# story id → { lang → { chapter index → translated text } }
TRANSLATIONS: dict[str, dict[str, dict[int, str]]] = {}

# ═══════════════════════════════════════════════════════════════════════
# The Glass Heron
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["the-glass-heron"] = {
    "pt-BR": {
        0: (
            "A água subiu numa terça-feira, o que Wren achou um dia sem graça para "
            "uma coisa tão grande acontecer. Ela tinha ido dormir com o rio onde o "
            "rio devia estar, lá embaixo depois das hortas, atrás dos salgueiros, "
            "fazendo o barulho que sempre fazia. Acordou com um barulho diferente. "
            "Era mais suave e muito mais perto, e vinha da escada. De manhã a viela "
            "era um rio e o rio não fazia ideia de que estava no lugar errado. "
            "Cuidava dos seus afazeres entre as casas exatamente como cuidava dos "
            "seus afazeres entre as margens, levando um painel de cerca, um "
            "engradado de plástico e uma bota de borracha verde, tudo na mesma "
            "velocidade sem pressa. A avó já tinha levado as cadeiras para cima. "
            "Tinha feito isso no escuro, sozinha, sem acordar ninguém, e estava "
            "tomando chá no patamar quando Wren apareceu de meias. — Não desça do "
            "quinto degrau para baixo — disse a avó. — O carpete está perdido e não "
            "quero você escorregando nele. Foi tudo. Sem pânico, sem explicação. Foi "
            "assim que Wren soube que já tinha acontecido antes. Da janela do "
            "patamar dava para ver o topo dos mourões, cada um com uma golinha de "
            "espuma. O galpão dos Henderson tinha se soltado e girado sozinho para "
            "ficar virado para o lado errado, o que lhe pareceu de algum modo mais "
            "grosseiro que a própria enchente. Mais além, onde devia estar a "
            "estrada, havia uma larga lâmina de água marrom seguindo quieta na "
            "direção dos campos. A cidade tinha virado um arquipélago da noite para "
            "o dia. Cada casa era uma ilha. As pessoas dentro delas ficavam nas "
            "janelas de cima e acenavam, e depois de um tempo pararam de acenar, "
            "porque só dá para acenar por certo tempo para alguém que você não "
            "alcança. Foi aí que ela viu o pássaro. Estava na cumeeira do telhado da "
            "casa em frente, com o pescoço dobrado para dentro dos ombros do jeito "
            "que as garças fazem quando decidiram esperar. Estava muito parada. No "
            "começo ela achou que fosse uma daquelas de plástico que as pessoas põem "
            "nos lagos para assustar os peixes. Então a luz se moveu, e atravessou. "
            "Era transparente de ponta a ponta, como uma garrafa erguida contra a "
            "janela. A manhã cinzenta entrava nela por cima e saía por baixo da cor "
            "do rio, um verde-marrom suave em movimento, como se alguma coisa "
            "estivesse sendo mexida lá dentro bem devagar. Wren não chamou ninguém. "
            "Teve a sensação forte, como às vezes se tem diante de um bicho selvagem "
            "que chegou perto, de que uma criatura daquelas devia poder chegar sem "
            "alarde. Se gritasse, a avó viria, e então a avó explicaria, e então "
            "seria uma coisa que tinha sido explicada. Então ficou na janela de "
            "meias olhando, e ela não olhou para Wren nenhuma vez, e depois de vinte "
            "minutos alçou voo, e as asas quando se abriram eram a coisa mais fina "
            "que ela já tinha visto, e atravessou a água até o telhado do número "
            "onze e se dobrou de novo. A avó veio e ficou ao lado dela, em algum "
            "momento, com uma segunda xícara de chá. — Ah — disse. — Então voltou. E "
            "desceu para cuidar do carpete, o que era, pensou Wren, uma coisa "
            "extraordinária de se dizer e depois simplesmente deixar ali largada."
        ),
        1: (
            "No segundo dia a gritaria tinha parado. Tinha sido divertido no primeiro "
            "dia, de um jeito sombrio. O senhor Adeyemi do número nove tinha uma voz "
            "que alcançava longe e gritava as notícias por cima da água como um "
            "pregoeiro: a luz tinha caído na parte de baixo, a venda tinha subido o "
            "estoque para a prateleira de cima, alguém tinha visto um lúcio passando "
            "nadando pela caixa de correio. As pessoas se debruçavam e riam. Mas "
            "gritar o dia inteiro deixa a pessoa rouca, e deixa cansada, e na tarde "
            "de quarta as janelas tinham silenciado e cada um estava sozinho na sua "
            "casa sendo sensato. Wren escreveu um bilhete. Fez isso mais para ter "
            "alguma coisa a fazer. Arrancou uma folha do fim do caderno e escreveu "
            "*vocês estão bem aí*, e não pôs nome nenhum porque não sabia para qual "
            "casa estava escrevendo. Dobrou bem pequeno e pôs no parapeito de fora "
            "debaixo de uma pedra. Fez do jeito que se joga uma moeda num poço. Sem "
            "esperar nada de verdade. Só fazendo. De manhã tinha sumido. No lugar "
            "havia um papel diferente, úmido numa ponta, dobrado do mesmo jeito. "
            "Dizia: *sim, e temos pão demais.* Wren ficou na janela com ele nas duas "
            "mãos por um tempo longo. Depois disso, ninguém precisou explicar nada a "
            "ninguém. Essa foi a parte estranha, a parte em que ela pensou durante "
            "anos depois — como uma coisa vira normal depressa quando é útil. Na "
            "quinta havia bilhetes em quatro parapeitos. Na sexta havia bilhetes em "
            "doze. A garça ia de telhado em telhado com seu passo longo e cuidadoso, "
            "e nunca tinha pressa, e nunca ia a uma casa que não tivesse posto "
            "alguma coisa para fora. Onde os pés dela tocavam a água na beira de um "
            "telhado, a água tinia, bem de leve, como uma taça batida com a colher. "
            "Se você estivesse prestando atenção, dava para saber em que parte da "
            "cidade ela estava. Os bilhetes não eram dramáticos. Era disso que Wren "
            "gostava neles. *Temos pão demais. A senhora Pryor está com tosse e sem "
            "mel. Alguém consegue chegar nos Kelly, ninguém viu luz na casa dos "
            "Kelly. Tem mel no número quatro, avisem a senhora Pryor. Os Kelly foram "
            "para a casa da filha no domingo, estão bem, parem de se preocupar com "
            "os Kelly.* E mais tarde, quando já durava cinco dias e todo mundo "
            "estava entediado e com medo em igual medida: *Tomas faz oito anos hoje "
            "e não tem bolo.* Uma dúzia de casas pôs alguma coisa no parapeito "
            "naquela noite. Wren viu a garça atravessar a água nove vezes antes de "
            "escurecer, indo mais devagar a cada vez, e uma vez chegou tão perto da "
            "janela dela que dava para ver o rio revolvendo dentro do peito. De "
            "manhã Tomas do número seis tinha uma coroa de papel, uma barra de "
            "chocolate, um desenho de cachorro assinado por alguém chamada Iris, um "
            "livro sobre submarinos com a primeira página arrancada, e quatro "
            "bilhetes separados que diziam *feliz aniversário* em quatro letras "
            "diferentes. A avó assistiu a tudo isso da cadeira do patamar sem muito "
            "comentário. — Ela não quer nada? — perguntou Wren. — Por fazer isso? A "
            "avó pensou naquilo com a seriedade que a pergunta merecia. — Alguns que "
            "ajudam — disse — não gostam que agradeçam. Não é grosseria. É só que "
            "agradecer transforma aquilo num favor, e nunca foi um favor. Sempre foi "
            "só a coisa que precisava ser feita."
        ),
        2: (
            "Na sexta noite a garça não veio. Wren pôs o bilhete no horário de "
            "sempre, debaixo da pedra de sempre, e ficou olhando o parapeito do "
            "patamar até a avó mandar ela dormir, e de manhã o bilhete ainda estava "
            "lá. Úmido, e enrolando na ponta, e por ler. No começo achou que tinha "
            "feito alguma coisa errada. Releu o próprio bilhete quatro vezes "
            "procurando o erro nele. Dizia: *a tosse da senhora Pryor piorou, alguém "
            "tem termômetro.* Pôs de novo na manhã seguinte com uma pedra em cima e "
            "foi à janela a cada vinte minutos. Às onze horas os parapeitos ao longo "
            "da viela tinham começado a encher. Dava para vê-los do patamar: "
            "quadrados brancos aparecendo no número quatro, no número nove, na casa "
            "dos Henderson, no número onze. Todo mundo tinha escrito alguma coisa. "
            "Todo mundo estava esperando. Não veio nada. É difícil descrever como "
            "foi aquele dia sem fazer parecer pior do que foi. Ninguém estava em "
            "perigo. A água não tinha subido; havia comida em todas as casas; a luz "
            "estava ligada na parte de cima da viela e as pessoas carregavam os "
            "telefones na casa dos Adeyemi passando por cima num gancho de "
            "varal. Nada tinha mudado de fato, exceto que treze bilhetes estavam "
            "sentados em catorze parapeitos molhando, e todo mundo podia ver o "
            "bilhete de todo mundo não sendo recolhido. A cidade tinha se "
            "acostumado em cinco dias. Era isso. Cinco dias não é nada — é menos que "
            "uma semana de aula — e tinha bastado para um modo inteiro de viver se "
            "estabelecer e começar a parecer permanente. A avó de Wren fez o almoço "
            "e não mencionou os bilhetes. Às quatro da tarde o senhor Adeyemi gritou "
            "por cima da água. Foi a primeira gritaria em três dias e soou "
            "enferrujada e alta demais, e ele perguntou se alguém tinha termômetro, "
            "e alguém do número quatro gritou de volta que tinha, e seguiu-se um "
            "negócio lento, difícil, de quarenta minutos, envolvendo um balde, um "
            "pedaço de corda de varal e um bocado de instrução sendo gritada de três "
            "direções ao mesmo tempo. O termômetro chegou seco na casa da senhora "
            "Pryor. A coisa toda tinha levado quarenta minutos e doze pessoas, e "
            "tinha funcionado, e Wren ficou na janela do patamar vendo o balde "
            "voltar pela água marrom na corda e entendeu uma coisa para a qual não "
            "teve palavras senão muito depois. A garça não estava fazendo uma coisa "
            "que eles não podiam fazer. Estava fazendo uma coisa que eles tinham "
            "parado de fazer. Ela disse isso à avó, mais ou menos, com palavras "
            "piores, durante o chá. A avó ouviu até o fim sem interromper, como "
            "sempre fazia, e depois disse: — Ela veio no ano em que eu tinha nove "
            "anos também. Quatro dias, daquela vez. E quando parou de vir, a viela "
            "esticou uma corda do portão dos Henderson até o nosso e deixou lá por "
            "seis anos. — Mexeu o chá. — Ainda estava lá quando sua mãe nasceu. "
            "Alguém tirou no fim porque tinha ficado verde. — Por que parou? — "
            "Tenho sessenta anos de pensar nisso e só tenho uma resposta, e você não "
            "vai gostar. Wren esperou. — Porque estávamos nos virando — disse a "
            "avó. A garça voltou na oitava noite. Wren viu do patamar por volta das "
            "seis da manhã, seguindo pela linha dos telhados das casas de número "
            "ímpar na luz cinzenta, sem pressa, exatamente como antes, recolhendo "
            "seis bilhetes molhados que a essa altura diziam coisas como *a corda "
            "funcionou, usem a corda* e *a senhora Pryor melhorou* e, do número "
            "seis, em letra de criança, *onde você foi.* Levou todos. Não trouxe "
            "nada de volta naquela manhã, até onde alguém pôde perceber. E a corda "
            "continuou esticada entre os portões, porque a essa altura as pessoas "
            "já tinham se acostumado com aquilo também."
        ),
        3: (
            "O rio foi embora do jeito que tinha vindo — sem pedir desculpa, ao longo "
            "de quatro dias lentos. Primeiro voltaram os mourões, depois o topo dos "
            "portões, depois os portões. A viela reapareceu debaixo de uma camada de "
            "lodo da cor de chá com leite, e cheirava a moeda fria e a alguma coisa "
            "mais velha por baixo. Havia um peixe no jardim dos Henderson e ninguém "
            "conseguia concordar sobre o que fazer com ele. Wren subiu ao patamar na "
            "última manhã, antes da escola, naquela parte cinzenta do dia em que "
            "tudo parece inacabado. A garça ainda estava lá. Mas tinha deixado de "
            "ser transparente. Estava na cumeeira do telhado em frente exatamente no "
            "lugar em que tinha estado na primeira manhã, e a luz não atravessava "
            "mais. Estava verde nas bordas e turva no meio, do jeito que o vidro "
            "fica quando o mar terminou com ele. Não havia nada se movendo dentro do "
            "peito dela. Ela atravessou a viela de bota por quinze centímetros de "
            "lodo e pegou a escada no galpão dos Henderson, que continuava virado "
            "para o lado errado, e subiu, o que não devia ter feito, e pôs a mão "
            "nela. Estava fria, e era mais pesada do que parecia, e não se mexeu. "
            "Desceu carregando debaixo de um braço com a escada balançando e pôs no "
            "mourão de canto no fim da viela, onde a luz vem pela estrada no fim da "
            "tarde. Ainda está lá. Alguém pôs uma laje de pedra embaixo com o tempo "
            "para não afundar quando o chão amolecesse. Quem passa acha que é um "
            "enfeite, e é, agora, mas também é uma garça. Os bilhetes foram para uma "
            "lata de biscoito debaixo da cama de Wren. Eram trinta e um, de doze "
            "casas diferentes, incluindo um que dizia *tem mel no número quatro* e "
            "um que só dizia *sim*. A avó disse que deviam guardar a lata em algum "
            "lugar sensato. Guardaram debaixo da cama."
        ),
    },
}

# ═══════════════════════════════════════════════════════════════════════
# Where the Moths Sleep
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["where-the-moths-sleep"] = {
    "pt-BR": {
        0: (
            "A luz do sótão estava acesa desde que qualquer um conseguia lembrar, e "
            "ninguém sabia dizer quem tinha acendido. Incomodava Ines mais do que "
            "incomodava qualquer outra pessoa. Ela tinha perguntado ao tio duas "
            "vezes. Na primeira ele tinha dito que era mais barato do que discutir "
            "sobre isso, o que não era uma resposta. Na segunda tinha dito que "
            "algumas coisas numa casa são mais velhas que as pessoas dentro dela, o "
            "que era menos resposta ainda que a primeira mas soava mais como uma. "
            "Dava para ver de noite do jardim — uma linha laranja fina em volta da "
            "borda do alçapão, pendurada no escuro do teto do patamar como o desenho "
            "de uma porta em vez de uma porta. Ela subiu na primeira noite quente do "
            "ano, porque o alçapão tinha começado a zumbir. Isso era novo. Era um "
            "som grave, não elétrico, mais parecido com o barulho que uma abelha faz "
            "dentro de um pote de geleia a três cômodos de distância. Tinha começado "
            "na terça e na sexta ela já sentia nos degraus da escada. Esperou o tio "
            "sair para trancar a estufa, e então subiu. O sótão estava cheio de "
            "mariposas. Não esvoaçando. Não se atirando feito bobas contra a "
            "lâmpada, que é o que mariposas fazem e a única coisa que Ines já tinha "
            "visto uma fazer. Estas estavam descansando. Centenas delas, dobradas "
            "rentes às vigas e à parte de baixo das telhas, asas fechadas, "
            "absolutamente imóveis, arranjadas do jeito que as páginas se arranjam "
            "num livro. Eram da cor de papel velho — algumas quase brancas, algumas "
            "do amarelo de uma página que ficou na janela, umas poucas quase "
            "marrons. Não se assustaram quando a cabeça dela apareceu pelo alçapão. "
            "Uma perto da mão dela se ajeitou muito de leve, do jeito que uma pessoa "
            "se remexe na cadeira. Ela sentou na beira do alçapão com as pernas para "
            "dentro, porque o assoalho não parecia confiável, e olhou para a mais "
            "próxima. Havia alguma coisa nas asas. Não um padrão. Ela sabia como são "
            "os padrões de mariposa: olhos e pintas e as carinhas falsas. Aquilo era "
            "um quadro. Um bem pequeno, pintado do jeito que um selo é impresso, "
            "atravessando as duas asas de modo que a emenda passava pelo meio dele. "
            "Era uma cozinha. Uma cozinha amarela com uma janela sobre a pia e uma "
            "cadeira puxada para fora da mesa. Olhou para a seguinte. Um barco, num "
            "mar cinzento, visto por trás. Olhou para a seguinte, e era um rosto que "
            "ela quase conhecia, e depois não, e o quase ficou com ela pela escada "
            "inteira até embaixo."
        ),
        1: (
            "Ela subiu de novo na noite seguinte, e na noite depois dessa. Na quarta "
            "noite já tinha descoberto como pegar uma. Você não pega uma mariposa; "
            "você encosta o dedo na parede ao lado dela e espera, e mais cedo ou "
            "mais tarde ela caminha para cima de você, sem pressa, como alguém "
            "subindo num ônibus. A que subiu no dedo dela na quarta noite tinha um "
            "corredor pintado nas asas. Um corredor comprido com uma passadeira, e "
            "no fim dele, uma porta verde. Ela segurou sob a lâmpada e olhou por um "
            "tempo longo. Quanto mais olhava, mais certeza tinha de que já tinha "
            "andado por aquele corredor. Sabia como era a luz na outra ponta à "
            "tarde. Sabia que a passadeira tinha uma parte gasta a dois terços do "
            "caminho e que dava para sentir através da meia. E exatamente ao mesmo "
            "tempo, com exatamente a mesma certeza, sabia que nunca tinha estado ali "
            "na vida. O tio subiu a escada atrás dela com duas canecas de chá, o que "
            "é uma coisa difícil de fazer e sugeria prática. Ele não pareceu "
            "surpreso com nada daquilo. Passou uma caneca para ela, sentou num "
            "engradado virado que claramente já tinha servido de assento muitas "
            "vezes, e olhou para a mariposa no dedo dela. — Porta verde — disse. — "
            "Essa é boa. Alguém sente falta dessa. Ines não disse nada, porque não "
            "conseguia pensar numa pergunta pequena o bastante para começar. — As "
            "pessoas deixam cair sonhos — disse o tio. — O tempo todo. Do jeito que "
            "se deixa cair uma luva do bolso: você não sente ir, só descobre depois "
            "que ficou só com uma. Acordar rápido demais, alguém falar seu nome, o "
            "despertador tocar na parte errada. E o sonho cai. — Bebeu um pouco de "
            "chá. — Eles têm que ir para algum lugar. Tudo tem que ir para algum "
            "lugar. Esta casa está recolhendo eles desde antes de ser minha, e antes "
            "de ser da minha mãe, e eu nunca entendi por que esta casa e não a do "
            "lado. — Quantas são? — Parei de contar lá por mil novecentos e noventa. "
            "Ines girou a mão devagar para a mariposa ficar nivelada. Na parede "
            "acima dela, cem asas pálidas seguravam cem quadros pequenos: uma "
            "bicicleta, um corredor de hospital, uma encosta com um muro "
            "atravessado, um casamento, um cachorro, uma loja que ela tinha quase "
            "certeza de ser a loja da Rua da Ponte mas com outras janelas. — Elas "
            "podem voltar? — disse. — Dá para devolver uma para alguém? O tio olhou "
            "para o chá um tempo. — Essa — disse — é a parte difícil."
        ),
        2: (
            "A que ela queria era o rosto. Tinha achado na primeira noite — terceira "
            "ao longo da viga, perto da chaminé — e tinha voltado a ela toda noite "
            "desde então, e toda noite acontecia a mesma coisa. Ela olhava e pensava "
            "*ah, esse é o* — e aí o nome não chegava. Era um homem. De meia-idade, "
            "ou chegando lá. Cabelo escuro recuando na frente. Estava olhando um "
            "pouco à esquerda de quem quer que o estivesse sonhando, e estava no "
            "meio de dizer alguma coisa, e as sobrancelhas estavam erguidas. Estava "
            "pintado melhor que as outras. Essa era a parte estranha. A cozinha e o "
            "barco e a porta verde estavam todos pintados do jeito que uma coisa é "
            "pintada de memória — as partes importantes nítidas, o resto vago. Esse "
            "tinha uma gola de camisa com um botão faltando na ponta, e uma "
            "cicatriz pequena atravessando uma sobrancelha, e aquele tipo de detalhe "
            "que só se consegue quando alguém olhou para um rosto durante anos e "
            "anos e anos. Ela perguntou ao tio quem era. Ele subiu e olhou um tempo "
            "com as mãos nos bolsos e disse que não fazia ideia, e que ele mesmo "
            "vinha se perguntando sobre aquela desde mais ou menos 2003. Ela fez a "
            "coisa sensata, o que levou três semanas. Desenhou — mal, depois menos "
            "mal, depois na quarta tentativa bem o bastante para ser reconhecível — "
            "e carregou o desenho pela cidade no bolso do casaco e mostrou para as "
            "pessoas. A mulher da padaria disse não. O homem da loja de bicicleta "
            "disse não, e depois segurou o desenho com o braço esticado e disse não "
            "de novo, mais devagar. O bibliotecário disse que ele parecia o irmão de "
            "alguém, o que não era útil. O padre Costa disse que ele parecia o irmão "
            "de todo mundo, o que era menos útil ainda. Um homem no ponto de ônibus "
            "disse que era um desenho muito bom, o que ela agradeceu mas não pôde "
            "usar para nada. No fim de três semanas tinha mostrado para trinta e uma "
            "pessoas e nenhuma delas o conhecia. Sentou no muro em frente à farmácia "
            "com o desenho no joelho e chegou à conclusão, e não gostou de chegar à "
            "conclusão. Só havia dois jeitos de aquilo terminar. Ou a pessoa que "
            "tinha deixado cair aquele sonho tinha se mudado — caso em que a "
            "mariposa ficaria naquela viga até a casa cair. Ou a pessoa que tinha "
            "deixado cair estava morta, e o sonho tinha se soltado do jeito que o "
            "último de qualquer coisa se solta, e tinha subido a ladeira e entrado "
            "por baixo das telhas e se dobrado contra uma viga, e não havia mais "
            "ninguém no mundo a quem pudesse ser entregue. Ela foi para casa e subiu "
            "a escada e sentou na beira do alçapão por um tempo longo. O tio subiu "
            "em algum momento com o chá. Não perguntou como tinha sido; tinha "
            "claramente deduzido como tinha sido pelo fato de ela estar sentada no "
            "escuro. — Tem umas quatrocentas assim — disse. — Que eu saiba. As que "
            "ninguém reclama. Não vão a lugar nenhum. Não morrem, até onde consigo "
            "ver: tenho uma lá em cima com uma carroça e não passa carroça nesta "
            "ladeira desde antes da guerra. — Então para que servem? — Elas não "
            "*servem* para nada — disse. — Essa é a parte que mais demorei a "
            "entender. Passei uns quinze anos tentando fazer este lugar ser útil e "
            "não cheguei a lugar nenhum, porque estava fazendo a pergunta errada. — "
            "Apontou com a cabeça para as vigas. — Não é um achados e perdidos. "
            "Ninguém vem ao balcão. É só onde elas param. Ines olhou para o homem de "
            "sobrancelhas erguidas, no meio de dizer alguma coisa, para alguém que o "
            "tinha amado o bastante para guardar o botão faltando. — Isso é triste "
            "— disse. — É — concordou o tio. — Mas olha o estado dele. Alguém "
            "gostava muitíssimo daquele homem. Isso continua verdade. É verdade "
            "agora, naquela viga, venha alguém buscar ou não. — Bebeu o chá. — Há "
            "coisas piores para se ter uma casa cheia."
        ),
        3: (
            "Levou quase o verão inteiro para descobrir, e descobrir não teve nada de "
            "mágico. Foi na maior parte fazer perguntas constrangedoras às pessoas e "
            "errar. As regras, até onde Ines chegou a estabelecer, eram estas. Uma "
            "mariposa não ia com qualquer um. Você podia levar uma nas mãos em "
            "concha até uma pessoa e abrir as mãos e ela ficava ali feito um pedaço "
            "de papel, completamente desinteressada, e mais cedo ou mais tarde "
            "voltava andando pela sua manga. Tinha que ser no lusco-fusco. Não "
            "escuro, não noite — lusco-fusco, os vinte minutos em que os postes já "
            "estão acesos mas você ainda enxerga a cor das coisas. E você tinha que "
            "estar perto de onde a pessoa estava quando perdeu. Essa era a parte que "
            "tornava difícil, porque significava descobrir quem, o que significava "
            "perguntar, e não há jeito bom de perguntar a um adulto se ele "
            "recentemente extraviou um sonho sobre um barco. Ela deu um jeito "
            "perguntando sobre os quadros. A mulher da padaria, quando Ines "
            "descreveu um mar cinzento visto da popa de um barco, parou de contar o "
            "troco e disse: — Meu pai tinha um barco assim — e depois: — Por quê? — "
            "e Ines disse que tinha visto uma pintura, o que era mentira, mas só uma "
            "pequena. Ela soltou a mariposa do barco em frente à padaria no "
            "lusco-fusco de uma quinta-feira. Entrou pela janela de cima, que estava "
            "aberta por causa do calor, e não saiu. O homem que consertava bicicleta "
            "tinha perdido o corredor com a porta verde. Ela tinha quase certeza "
            "antes de perguntar e certeza completa depois, pelo jeito como ele disse "
            "\"essa era a casa da minha avó\" e então parou de falar e voltou a "
            "centrar a roda que estava centrando. Ela soltou em frente à loja dele "
            "na noite seguinte. Ele ainda estava lá, trabalhando até tarde, e não a "
            "viu fazer. Ela assistiu do outro lado da rua a mariposa entrar por "
            "baixo da porta de enrolar. Ele saiu mais ou menos um minuto depois e "
            "ficou na calçada, olhando para nada em particular, por um bom tempo. "
            "Depois entrou de novo e voltou para a roda. Ele nunca comentou com ela, "
            "e ela nunca comentou com ele, e por mais ou menos um ano depois disso "
            "ele fez os cabos de freio dela de graça e nenhum dos dois jamais disse "
            "por quê. Ela fez dezenove naquele verão. Dezenove de centenas, e levou "
            "de junho até meados de setembro, e errou quatro e teve que trazer de "
            "volta. No fim subiu a escada uma última noite antes das aulas "
            "começarem, esperando — não sabia bem o quê. Alguma falha visível. "
            "Algum vão nas vigas onde dezenove costumavam estar. O sótão estava "
            "exatamente igual. — Sempre está — disse o tio, do engradado. — Isso não "
            "é motivo para não fazer. E ele deixou a luz acesa, do jeito que sempre "
            "tinha sido deixada acesa, e desceram e fecharam o alçapão, e o zumbido "
            "seguiu bem baixinho acima deles a noite toda, do jeito que seguia havia "
            "anos, do jeito que presumivelmente ainda segue."
        ),
    },
}

# ═══════════════════════════════════════════════════════════════════════
# The Cat Who Walks You Home
# ═══════════════════════════════════════════════════════════════════════
TRANSLATIONS["the-cat-who-walks-you-home"] = {
    "pt-BR": {
        0: (
            "O poste em frente ao número quarenta estava apagado desde fevereiro e a "
            "prefeitura tinha um número de protocolo para ele. Bruno sabia o número "
            "de protocolo de cor porque a mãe tinha dito ao telefone treze vezes, e "
            "a cada vez tinha dito um pouco mais devagar, e a cada vez uma pessoa "
            "diferente tinha dito a ela que estava registrado. O que o número de "
            "protocolo significava, na prática, era que os últimos sessenta metros "
            "da Rua da Cordoaria eram escuros. Não era assustador em outubro. Em "
            "outubro você descia do ônibus às quatro e meia e a luz ainda estava "
            "indo embora. No fim de novembro já era escuro de verdade às cinco e os "
            "sessenta metros tinham virado uma coisa em que Bruno pensava no ônibus, "
            "a partir de umas três paradas antes. Não havia nada ali. Ele sabia "
            "disso. Sabia do jeito que se sabem as coisas que não fazem a menor "
            "diferença: havia um muro de um lado, e os fundos do depósito de "
            "azulejos do outro, e um vão de porta, e a esquina. Não havia ninguém "
            "ali. Nunca tinha acontecido nada ali. Era só escuro, e escuro em que "
            "você entra sozinho aos onze anos é uma substância específica, mais "
            "pesada que a outra. Ele tinha chegado a várias conclusões sobre aquilo "
            "no fim de novembro. A primeira era que correr piorava. Tinha tentado "
            "correr na primeira semana e tinha chegado à esquina com o coração "
            "disparado e a mochila batendo no quadril e a sensação muito forte de "
            "ter confirmado alguma coisa. Andar era melhor. Andar era uma "
            "declaração. A segunda era que o vão de porta era a parte difícil. "
            "Ficava recuado uns um metro da calçada, e era o único lugar nos "
            "sessenta metros inteiros onde podia haver alguma coisa que você não "
            "veria até estar na altura. Ele tinha desenvolvido, sem nunca ter "
            "decidido, o hábito de andar pelo outro lado da rua e virar a cabeça "
            "para lá no último instante. Levava meio segundo. Fez isso toda "
            "santa noite durante quatro meses. A terceira coisa era que nada daquilo "
            "era razoável, e ele sabia que não era razoável, e saber não fazia a "
            "menor diferença. Ele gostaria que isso constasse. Não era uma criança "
            "pequena. Tinha passado por aquele vão de porta à luz do dia umas "
            "quatrocentas vezes sem pensar nada. O saber ficava num lugar e o andar "
            "acontecia em outro, e os dois não conversavam. Ele viu o gato pela "
            "primeira vez numa quinta-feira no começo de dezembro. Tinha feito a "
            "curva perto da farmácia e parado, do jeito que tinha começado a parar, "
            "para o pequeno assunto particular de decidir andar. E lá, na outra "
            "ponta, bem na esquina onde a luz voltava, alguma coisa estava sentada. "
            "Era cinza e era comum e estava virada para ele. Ele andou. Ela ficou. "
            "Chegou mais ou menos no meio e ela levantou, sem pressa, e virou, e "
            "andou dobrando a esquina à frente dele — não indo embora, exatamente, "
            "mais no passo de quem presume que você vem junto — e quando ele dobrou "
            "a esquina para a luz ela estava sentada de novo, dez metros adiante, "
            "esperando. Ele disse: — Oi. Ela olhou para ele. Ele estendeu a mão, do "
            "jeito que se faz, e fez o barulho, e ela levantou e foi embora rente ao "
            "muro e sumiu entre dois carros estacionados."
        ),
        1: (
            "Ele comentou na escola e descobriu, ao longo de mais ou menos uma "
            "semana, que aquilo não era um fenômeno novo e que cada um tinha uma "
            "versão ligeiramente diferente. Inês tinha um na escadaria atrás do "
            "mercado. O dela era preto e ela chamava de Senhor e tinha subido a "
            "escadaria com ela toda noite em janeiro, quando o pai estava "
            "trabalhando até tarde. Teodoro disse que o dele era laranja e morava "
            "perto do campo de futebol e só aparecia quando chovia, sobre o que ele "
            "tinha uma teoria. As gêmeas do ano acima disseram que nunca tinham "
            "visto gato nenhum mas que a mãe delas tinha visto, quando era pequena, "
            "na estrada que vai para a pedreira, e que na versão dela ele tinha "
            "saído de debaixo de um carro e ido com ela o caminho todo até o "
            "entroncamento e não estava mais lá quando ela se virou. A única regra "
            "que estava em todas as versões, e Bruno conferiu, era esta: ele nunca "
            "vinha quando você chamava. Ele juntou doze relatos até o fim de janeiro "
            "e escreveu no fim do caderno de português, sob um título que depois "
            "rabiscou porque parecia infantil. Cinza, preto, laranja, rajado, e um "
            "sobre o qual Rita não abria mão: branco, com o rosto cinza. Ruas "
            "diferentes. Anos diferentes. O da mãe das gêmeas era de mais ou menos "
            "1994, o que fazia dele ou um gato muito velho ou, como Teodoro "
            "observou em considerável volume no corredor, não um gato. Ninguém tinha "
            "tocado num. Ele conferiu isso especificamente, porque tinha estendido a "
            "mão na primeira noite e tinha se sentido bobo por uma semana depois. "
            "Ninguém tinha. Eles chegavam a uns dois metros e ficavam a dois metros "
            "e sumiam assim que você estava na luz. Ninguém tinha visto um chegar, "
            "tampouco. Isso ele demorou mais a notar, porque é uma coisa difícil de "
            "notar, a ausência. Em todos os doze relatos o gato simplesmente já "
            "estava lá, sentado, na outra ponta, virado para você. Não vindo andando. "
            "Não saindo de debaixo de nada. Sentado, no lugar onde o escuro "
            "terminava, já olhando para você antes de você olhar para ele. Você "
            "podia ficar no alto da rua às oito da noite quando estava perfeitamente "
            "bem e dizer *psiu, psiu, psiu* até se sentir bobo, e não acontecia "
            "nada. Teodoro tinha tentado com comida. Inês tinha tentado uma semana "
            "seguida em fevereiro por pura curiosidade científica e não ganhou nada "
            "além de um resfriado. E então numa noite em que você estava com medo, "
            "ele estava lá. A avó de Bruno, que foi a única adulta a quem ele "
            "contou, ouviu tudo até o fim com as mãos na pia e depois disse uma "
            "coisa que ele não entendeu por uns quatro anos. Disse: — Não é o gato "
            "que muda. Ele perguntou o que aquilo deveria significar. Ela secou um "
            "copo e pôs no escorredor e não respondeu por tempo suficiente para ele "
            "supor que não ia responder. — Quando eu era menina — disse —, havia uma "
            "mulher nesta rua que não conseguia sair depois de escurecer de jeito "
            "nenhum. Não que não quisesse: não conseguia. Alguma coisa tinha "
            "acontecido com ela, antes, em outro lugar, e ninguém na rua nunca soube "
            "o quê, e não era da nossa conta. E por uns vinte anos, sempre que ela "
            "precisava ir a algum lugar de noite, um dos homens calhava de estar no "
            "alto da escadaria fumando um cigarro. Homens diferentes. Nunca o mesmo "
            "duas vezes seguidas. Nunca combinado, até onde eu pude perceber. — Não "
            "é a mesma coisa. — Não — concordou a avó. — Não é. E deu o pano a ele "
            "para secar, que era como as conversas terminavam naquela cozinha."
        ),
        2: (
            "Em março os dias ficaram mais longos e os sessenta metros voltaram a ser "
            "sessenta metros. Bruno notou isso só do jeito que se nota que um dente "
            "parou de doer, ou seja, tarde, e por acidente. Estava subindo do ônibus "
            "numa terça e estava pensando numa coisa que tinha acontecido na aula de "
            "matemática, e fez a curva perto da farmácia e não parou. Estava quase no "
            "fim quando percebeu que não tinha olhado para a esquina. Parou então, no "
            "meio da parte escura, e se virou, e olhou direito para onde tinha vindo "
            "e para onde estava indo, e não havia nada em nenhuma das direções. O "
            "depósito de azulejos. O muro. O vão de porta. As lixeiras. O gato não "
            "estava lá. Ficou ali um tempo, e sentiu — e ele nunca conseguiu fazer "
            "isso soar sensato — um pouco rejeitado. Voltou na noite seguinte de "
            "propósito. Desceu pelo meio da rua devagar, olhando cada parte dela por "
            "vez: o muro, os fundos do depósito, as lixeiras, o vão de porta. Ficou "
            "dentro do vão de porta por um minuto inteiro, o que ele nunca tinha "
            "feito na vida, e descobriu que era um vão de porta com um degrau gasto "
            "e umas folhas no canto e um ferrolho pintado por cima umas nove vezes. "
            "Disse *psiu*, duas vezes, baixinho, se sentindo ridículo. Havia um carro "
            "em algum lugar lá na avenida, e a televisão de alguém através de uma "
            "janela, e esse era o conteúdo inteiro da Rua da Cordoaria às seis e dez "
            "de uma quarta-feira de março. Tentou de novo em abril, com um pedaço de "
            "chouriço, do que ele ainda tem vergonha. Disse, para a rua vazia: — Eu "
            "ainda estou aqui, sabia. Não aconteceu nada, que é o que acontece. Foi "
            "para casa e jantou e não comentou, e levou até mais ou menos abril para "
            "entender que o gato não tinha parado de vir. Ele tinha parado de "
            "precisar. Eram dois acontecimentos completamente diferentes que tinham "
            "parecido, de dentro, o mesmo."
        ),
        3: (
            "No inverno seguinte a luz em frente ao número quarenta continuava "
            "apagada e havia um número de protocolo novo. Bruno tinha doze anos a "
            "essa altura e tinha parado de pensar nos sessenta metros por completo, e "
            "a razão de ele lembrar qualquer coisa disso é uma menina chamada Cátia "
            "que se mudou para os apartamentos acima da farmácia em outubro e que "
            "tinha nove anos. Ele reparou nela porque ela parou. Fez a curva uma "
            "noite por volta das cinco e meia e havia uma pessoa pequena parada no "
            "alto da parte escura com a mochila apertada contra o peito nos dois "
            "braços, fazendo o assunto particular de decidir, e não decidindo. Ele "
            "sabia exatamente o que ela estava fazendo. Tinha feito por quatro meses. "
            "Não disse nada sobre isso, porque tinha doze anos e sabia que seria a "
            "coisa errada. Passou por ela e disse \"boa noite\" e seguiu em "
            "velocidade normal, e ela veio atrás dele, uns quatro metros atrás, o "
            "caminho todo até dobrar a esquina para a luz. Ela fez isso toda noite "
            "por umas três semanas, a quatro metros, e nenhum dos dois jamais "
            "mencionou. E então numa noite no começo de dezembro ele estava "
            "atrasado — tinha ficado para o futebol e pegado o ônibus mais tarde — e "
            "fez a curva quase às sete, e a parte escura estava escura de verdade, e "
            "não havia ninguém nela. E na outra ponta, na esquina onde a luz voltava, "
            "alguma coisa cinza estava sentada virada para ele. Bruno parou. Ficou "
            "ali no alto da Rua da Cordoaria por um tempo, bem mais do que precisava, "
            "olhando sessenta metros de escuro abaixo para um gato que não via havia "
            "um ano e meio. Então andou. Ele levantou quando Bruno estava na metade, "
            "sem pressa, e dobrou a esquina à frente dele no passo de quem presume "
            "que você vem junto, e quando ele entrou na luz estava sentado dez metros "
            "adiante. Ele não estendeu a mão dessa vez. Tinha aprendido isso pelo "
            "menos. Disse: — Eu sei. Estou indo. E ele olhou para Bruno, e levantou, "
            "e foi embora rente ao muro e sumiu entre dois carros estacionados. Ele "
            "contou à avó naquela noite, porque ela continuava sendo a única adulta a "
            "quem ele contava, e ela estava fazendo a mesma coisa na mesma pia. — Ele "
            "voltou — disse. — Eu tenho doze anos. — Hum — disse a avó. — Mas eu não "
            "estava com medo. Eu estava atrasado, só isso. Eu só estava atrasado. A "
            "avó fechou a torneira e secou as mãos e olhou para ele por um instante "
            "com uma expressão que ele não conseguiu ler de jeito nenhum. — Bruno — "
            "disse. — Você estava sozinho, no escuro, e você tem doze anos, e você "
            "ficou parado no alto daquela rua por um minuto inteiro antes de se "
            "mexer. Eu vi da janela. — Pendurou o pano no varão. — Não é o gato que "
            "muda."
        ),
    },
}

# ═══════════════════════════════════════════════════════════════════════
# S01 — the three free stories in Spanish
# ═══════════════════════════════════════════════════════════════════════

TRANSLATIONS["the-glass-heron"]["es"] = {
    0: (
        "El agua subió un martes, lo que a Wren le pareció un día poco memorable "
        "para que ocurriera algo tan grande. Se había ido a dormir con el río donde "
        "el río debía estar, allá abajo pasadas las huertas, detrás de los sauces, "
        "haciendo el ruido que siempre hacía. Se despertó con un ruido distinto. Era "
        "más suave y mucho más cercano, y venía de la escalera. Por la mañana el "
        "callejón era un río y el río no tenía idea de que estaba en el lugar "
        "equivocado. Se ocupaba de sus asuntos entre las casas exactamente como se "
        "ocupaba de sus asuntos entre las orillas, llevando un panel de valla, una "
        "caja de plástico y una bota de agua verde, todo a la misma velocidad sin "
        "prisa. Su abuela ya había subido las sillas. Lo había hecho a oscuras, "
        "sola, sin despertar a nadie, y estaba tomando té en el descansillo cuando "
        "Wren salió en calcetines. —No bajes del quinto escalón —dijo su abuela—. La "
        "alfombra está perdida y no quiero que resbales. Eso fue todo. Sin pánico, "
        "sin explicación. Así supo Wren que ya había pasado antes. Desde la ventana "
        "del descansillo se veían las puntas de los postes de la valla, cada uno con "
        "un pequeño collar de espuma. El cobertizo de los Henderson se había soltado "
        "y había girado solo hasta quedar mirando al revés, lo que le resultó de "
        "algún modo más grosero que la inundación misma. Más allá, donde debía estar "
        "la carretera, había una ancha lámina de agua marrón que se iba en silencio "
        "hacia los campos. El pueblo se había convertido en un archipiélago de la "
        "noche a la mañana. Cada casa era una isla. La gente dentro se asomaba a las "
        "ventanas de arriba y saludaba con la mano, y al cabo de un rato dejó de "
        "saludar, porque solo se puede saludar durante cierto tiempo a alguien a "
        "quien no puedes alcanzar. Fue entonces cuando vio el pájaro. Estaba en el "
        "caballete del tejado de la casa de enfrente, con el cuello doblado hacia "
        "dentro de los hombros como hacen las garzas cuando han decidido esperar. "
        "Estaba muy quieta. Al principio pensó que era una de esas de plástico que "
        "la gente pone en los estanques para asustar a los peces. Entonces la luz se "
        "movió, y la atravesó. Era transparente de lado a lado, como una botella "
        "puesta contra una ventana. La mañana gris entraba por arriba y salía por "
        "abajo del color del río, un verde pardo suave en movimiento, como si algo "
        "estuviera siendo removido dentro muy despacio. Wren no llamó a nadie. Tuvo "
        "la fuerte sensación, como se tiene a veces ante un animal salvaje que se ha "
        "acercado, de que a una criatura así había que dejarla llegar sin alboroto. "
        "Si gritaba, vendría su abuela, y entonces su abuela lo explicaría, y "
        "entonces sería una cosa que había sido explicada. Así que se quedó en la "
        "ventana en calcetines y la miró, y ella no la miró ni una vez, y al cabo de "
        "veinte minutos alzó el vuelo, y sus alas al abrirse fueron la cosa más "
        "delgada que había visto nunca, y cruzó el agua hasta el tejado del número "
        "once y se plegó de nuevo. Su abuela vino y se puso a su lado, en algún "
        "momento, con una segunda taza de té. —Ah —dijo—. Ha vuelto, entonces. Y "
        "bajó a ocuparse de la alfombra, lo cual era, pensó Wren, una cosa "
        "extraordinaria de decir y luego simplemente dejar ahí tirada."
    ),
    1: (
        "Para el segundo día los gritos habían cesado. El primer día había sido "
        "divertido, de un modo sombrío. El señor Adeyemi del número nueve tenía una "
        "voz que llegaba lejos y había gritado las noticias por encima del agua como "
        "un pregonero: la luz se había ido en la parte baja, la tienda había subido "
        "las existencias al estante de arriba, alguien había visto un lucio pasando "
        "nadando por el buzón. La gente se asomaba y se reía. Pero gritar todo el "
        "día deja ronca a una persona, y la deja cansada, y el miércoles por la "
        "tarde las ventanas se habían quedado calladas y cada uno estaba solo en su "
        "casa siendo sensato. Wren escribió una nota. Lo hizo sobre todo por tener "
        "algo que hacer. Arrancó una hoja del final de un cuaderno y escribió "
        "*estáis bien ahí*, y no puso ningún nombre porque no sabía a qué casa "
        "estaba escribiendo. La dobló muy pequeña y la puso en el alféizar de fuera "
        "bajo una piedra. Lo hizo como se echa una moneda a un pozo. Sin esperar "
        "nada de verdad. Solo haciéndolo. Por la mañana no estaba. En su lugar había "
        "un papel distinto, húmedo en una esquina, doblado igual. Decía: *sí, y "
        "tenemos pan de sobra.* Wren se quedó en la ventana con él en las dos manos "
        "un buen rato. Después de eso, nadie necesitó explicarle nada a nadie. Esa "
        "fue la parte extraña, la parte en la que pensó durante años después: lo "
        "rápido que una cosa se vuelve normal cuando es útil. El jueves había notas "
        "en cuatro alféizares. El viernes había notas en doce. La garza iba de "
        "tejado en tejado con su paso largo y cuidadoso, y nunca tenía prisa, y "
        "nunca iba a una casa que no hubiera puesto algo fuera. Donde sus patas "
        "tocaban el agua en el borde de un tejado, el agua sonaba, muy levemente, "
        "como una copa golpeada con una cuchara. Si estabas atento, sabías en qué "
        "parte del pueblo estaba. Las notas no eran dramáticas. Eso era lo que a "
        "Wren le gustaba de ellas. *Tenemos pan de sobra. La señora Pryor tiene tos "
        "y no tiene miel. ¿Alguien llega a los Kelly? Nadie ha visto luz en casa de "
        "los Kelly. Hay miel en el número cuatro, decídselo a la señora Pryor. Los "
        "Kelly se fueron a casa de su hija el domingo, están bien, dejad de "
        "preocuparos por los Kelly.* Y más tarde, cuando ya llevaba cinco días y "
        "todo el mundo estaba aburrido y asustado a partes iguales: *Tomas cumple "
        "ocho hoy y no hay tarta.* Una docena de casas puso algo en el alféizar esa "
        "noche. Wren vio a la garza cruzar el agua nueve veces antes de que "
        "oscureciera, cada vez más despacio, y una vez se acercó tanto a su ventana "
        "que se veía el río revolviéndose dentro de su pecho. Por la mañana Tomas "
        "del número seis tenía una corona de papel, una tableta de chocolate, un "
        "dibujo de un perro firmado por alguien llamada Iris, un libro sobre "
        "submarinos con la primera página arrancada, y cuatro notas distintas que "
        "decían *feliz cumpleaños* con cuatro letras distintas. Su abuela vio todo "
        "esto desde la silla del descansillo sin mucho comentario. —¿No quiere nada? "
        "—preguntó Wren—. ¿Por hacerlo? Su abuela lo pensó con la seriedad que la "
        "pregunta merecía. —Algunos que ayudan —dijo— no quieren que se les "
        "agradezca. No es descortesía. Es que agradecer lo convierte en un favor, y "
        "nunca fue un favor. Solo fue siempre lo que había que hacer."
    ),
    2: (
        "La sexta noche la garza no vino. Wren puso su nota a la hora de siempre, "
        "bajo la piedra de siempre, y vigiló el alféizar desde el descansillo hasta "
        "que su abuela la mandó a la cama, y por la mañana la nota seguía ahí. "
        "Húmeda, y curvada en la esquina, y sin leer. Al principio pensó que había "
        "hecho algo mal. Releyó su propia nota cuatro veces buscando el error. "
        "Decía: *la tos de la señora Pryor ha empeorado, ¿alguien tiene termómetro?* "
        "La volvió a poner a la mañana siguiente con una piedra encima y fue a la "
        "ventana cada veinte minutos. A las once los alféizares del callejón habían "
        "empezado a llenarse. Se veían desde el descansillo: cuadrados blancos "
        "apareciendo en el número cuatro, en el número nueve, en casa de los "
        "Henderson, en el número once. Todo el mundo había escrito algo. Todo el "
        "mundo estaba esperando. No vino nada. Es difícil describir cómo fue aquel "
        "día sin hacerlo sonar peor de lo que fue. Nadie estaba en peligro. El agua "
        "no había subido; había comida en todas las casas; la luz funcionaba en la "
        "parte alta del callejón y la gente cargaba los teléfonos en casa de los "
        "Adeyemi pasándolos por encima con un gancho de tender. No había cambiado "
        "nada en realidad, salvo que trece notas estaban sentadas en catorce "
        "alféizares mojándose, y todo el mundo podía ver la nota de todo el mundo "
        "sin ser recogida. El pueblo se había acostumbrado en cinco días. Eso era lo "
        "que pasaba. Cinco días no son nada —son menos que una semana de colegio— y "
        "habían bastado para que toda una forma de vivir se estableciera y empezara "
        "a parecer permanente. La abuela de Wren hizo la comida y no mencionó las "
        "notas. A las cuatro el señor Adeyemi gritó por encima del agua. Fue el "
        "primer grito en tres días y sonó oxidado y demasiado alto, y preguntó si "
        "alguien tenía un termómetro, y alguien del número cuatro le gritó que sí, y "
        "siguió un asunto lento, difícil, de cuarenta minutos, con un cubo, un trozo "
        "de cuerda de tender y una gran cantidad de instrucciones gritadas desde "
        "tres direcciones a la vez. El termómetro llegó seco a casa de la señora "
        "Pryor. La cosa entera había llevado cuarenta minutos y doce personas, y "
        "había funcionado, y Wren se quedó en la ventana del descansillo viendo el "
        "cubo volver por el agua marrón en la cuerda y entendió algo para lo que no "
        "tuvo palabras hasta mucho después. La garza no había estado haciendo algo "
        "que ellos no pudieran hacer. Había estado haciendo algo que ellos habían "
        "dejado de hacer. Se lo dijo a su abuela, más o menos, con peores palabras, "
        "con el té. Su abuela escuchó hasta el final sin interrumpir, como hacía "
        "siempre, y luego dijo: —Vino el año en que yo tenía nueve años, también. "
        "Cuatro días aquella vez. Y cuando dejó de venir, el callejón tendió una "
        "cuerda desde el portón de los Henderson hasta el nuestro y la dejó seis "
        "años. —Removió el té—. Todavía estaba ahí cuando nació tu madre. Alguien la "
        "quitó al final porque se había puesto verde. —¿Por qué paró? —He tenido "
        "sesenta años para pensarlo y solo tengo una respuesta, y no te va a gustar. "
        "Wren esperó. —Porque nos las arreglábamos —dijo su abuela. La garza volvió "
        "la octava noche. Wren la vio desde el descansillo hacia las seis de la "
        "mañana, recorriendo la línea de tejados de las casas impares en la luz "
        "gris, sin prisa, exactamente igual que antes, recogiendo seis notas mojadas "
        "que para entonces decían cosas como *la cuerda funcionó, usad la cuerda* y "
        "*la señora Pryor está mejor* y, del número seis, con letra de niño, *dónde "
        "has ido.* Se las llevó todas. No trajo nada de vuelta aquella mañana, hasta "
        "donde nadie pudo notar. Y la cuerda se quedó tendida entre los portones, "
        "porque para entonces la gente también se había acostumbrado a eso."
    ),
    3: (
        "El río se fue como había venido: sin disculparse, a lo largo de cuatro días "
        "lentos. Primero volvieron los postes de la valla, luego la parte de arriba "
        "de los portones, luego los portones. El callejón reapareció bajo una capa "
        "de limo del color del té con leche, y olía a monedas frías y a algo más "
        "viejo por debajo. Había un pez en el jardín de los Henderson y nadie se "
        "ponía de acuerdo sobre qué hacer con él. Wren subió al descansillo la "
        "última mañana, antes del colegio, en esa parte gris del día en que todo "
        "parece sin terminar. La garza seguía ahí. Pero había dejado de ser "
        "transparente. Estaba en el caballete del tejado de enfrente exactamente en "
        "el sitio en que había estado la primera mañana, y la luz ya no la "
        "atravesaba. Estaba verde en los bordes y turbia en el medio, como se pone "
        "el vidrio cuando el mar ha terminado con él. No había nada moviéndose "
        "dentro de su pecho. Cruzó el callejón con las botas por quince centímetros "
        "de limo y cogió la escalera del cobertizo de los Henderson, que seguía "
        "mirando al revés, y subió, lo cual no debía hacer, y le puso la mano "
        "encima. Estaba fría, y pesaba más de lo que parecía, y no se movió. La bajó "
        "bajo un brazo con la escalera tambaleándose y la puso en el poste de la "
        "esquina al final del callejón, donde la luz entra por la carretera a última "
        "hora de la tarde. Sigue ahí. Alguien le puso una losa debajo con el tiempo "
        "para que no se hundiera cuando el suelo se ablandara. Quien pasa da por "
        "hecho que es un adorno, y lo es, ahora, pero también es una garza. Las "
        "notas fueron a una lata de galletas bajo la cama de Wren. Eran treinta y "
        "una, de doce casas distintas, incluida una que decía *hay miel en el número "
        "cuatro* y una que solo decía *sí*. Su abuela dijo que deberían guardar la "
        "lata en algún sitio sensato. La guardaron bajo la cama."
    ),
}

TRANSLATIONS["where-the-moths-sleep"]["es"] = {
    0: (
        "La luz del desván llevaba encendida desde que nadie recordaba, y nadie "
        "sabía decir quién la había encendido. A Ines le molestaba más que a nadie. "
        "Se lo había preguntado a su tío dos veces. La primera él le dijo que salía "
        "más barato que discutirlo, lo cual no era una respuesta. La segunda dijo "
        "que algunas cosas en una casa son más viejas que la gente que vive en ella, "
        "lo cual era menos respuesta que la primera pero sonaba más a una. Se veía "
        "de noche desde el jardín: una línea naranja fina alrededor del borde de la "
        "trampilla, colgada en la oscuridad del techo del descansillo como el dibujo "
        "de una puerta más que como una puerta. Subió la primera noche cálida del "
        "año, porque la trampilla había empezado a zumbar. Eso era nuevo. Era un "
        "sonido grave, no eléctrico, más parecido al ruido que hace una abeja dentro "
        "de un tarro de mermelada a tres habitaciones de distancia. Había empezado "
        "el martes y para el viernes lo notaba en los peldaños de la escalera. "
        "Esperó a que su tío saliera a cerrar el invernadero, y subió. El desván "
        "estaba lleno de polillas. No revoloteando. No dándose de bruces contra la "
        "bombilla, que es lo que hacen las polillas y lo único que Ines había visto "
        "hacer a una. Estas descansaban. Cientos de ellas, plegadas planas contra "
        "las vigas y la cara interior de las tejas, alas cerradas, absolutamente "
        "quietas, dispuestas como se disponen las páginas en un libro. Eran del "
        "color del papel viejo: algunas casi blancas, algunas del amarillo de una "
        "página que ha estado en una ventana, unas pocas casi marrones. No se "
        "asustaron cuando la cabeza de Ines asomó por la trampilla. Una cerca de su "
        "mano se acomodó muy levemente, como se remueve una persona en una silla. Se "
        "sentó en el borde de la trampilla con las piernas colgando, porque el suelo "
        "no parecía de fiar, y miró a la más cercana. Había algo en sus alas. No un "
        "dibujo. Ella sabía cómo son los dibujos de las polillas: ojos y motas y las "
        "pequeñas caras falsas. Aquello era un cuadro. Uno muy pequeño, pintado como "
        "se imprime un sello, cruzando las dos alas de modo que la juntura pasaba "
        "por el medio. Era una cocina. Una cocina amarilla con una ventana sobre el "
        "fregadero y una silla apartada de la mesa. Miró a la siguiente. Un barco, "
        "en un mar gris, visto desde atrás. Miró a la siguiente, y era una cara que "
        "casi conocía, y luego no, y el casi se quedó con ella toda la escalera "
        "abajo."
    ),
    1: (
        "Subió otra vez la noche siguiente, y la noche después. Para la cuarta noche "
        "ya había averiguado cómo coger una. A una polilla no se la atrapa; pones el "
        "dedo contra la pared a su lado y esperas, y tarde o temprano se sube a ti, "
        "sin prisa, como alguien subiendo a un autobús. La que se le subió al dedo "
        "la cuarta noche tenía un pasillo pintado en las alas. Un pasillo largo con "
        "una alfombra de tira, y al final, una puerta verde. La sostuvo bajo la "
        "bombilla y la miró un buen rato. Cuanto más miraba, más segura estaba de "
        "haber recorrido aquel pasillo. Sabía cómo era la luz al fondo por la tarde. "
        "Sabía que la alfombra tenía una zona gastada a dos tercios del camino y que "
        "se notaba a través de los calcetines. Y exactamente al mismo tiempo, con "
        "exactamente la misma certeza, sabía que nunca había estado allí en su vida. "
        "Su tío subió la escalera detrás de ella con dos tazas de té, lo cual es "
        "difícil de hacer y sugería práctica. No pareció sorprendido por nada de "
        "aquello. Le dio una taza, se sentó en una caja del revés en la que "
        "claramente se había sentado muchas veces, y miró la polilla en el dedo de "
        "Ines. —Puerta verde —dijo—. Esa es buena. Alguien echa esa de menos. Ines "
        "no dijo nada, porque no se le ocurría una pregunta lo bastante pequeña para "
        "empezar. —La gente se deja caer sueños —dijo su tío—. Todo el tiempo. Como "
        "se te cae un guante del bolsillo: no lo notas irse, solo descubres luego "
        "que te ha quedado uno. Despertarse demasiado rápido, que alguien diga tu "
        "nombre, que suene el despertador en la parte equivocada. Y el sueño se "
        "cae. —Bebió un poco de té—. Tienen que ir a alguna parte. Todo tiene que ir "
        "a alguna parte. Esta casa lleva recogiéndolos desde antes de ser mía, y "
        "antes de ser de mi madre, y nunca he averiguado por qué esta casa y no la "
        "de al lado. —¿Cuántas hay? —Dejé de contar hacia mil novecientos noventa. "
        "Ines giró la mano despacio para que la polilla quedara nivelada. En la "
        "pared, encima de ella, cien alas pálidas sostenían cien cuadros pequeños: "
        "una bicicleta, un pasillo de hospital, una ladera con un muro cruzándola, "
        "una boda, un perro, una tienda que estaba casi segura de que era la tienda "
        "de la calle del Puente pero con otras ventanas. —¿Pueden volver? —dijo—. "
        "¿Se le puede devolver una a alguien? Su tío miró su té un rato. —Eso —dijo— "
        "es la parte difícil."
    ),
    2: (
        "La que ella quería era la cara. La había encontrado la primera noche —la "
        "tercera a lo largo de la viga, cerca de la chimenea— y había vuelto a ella "
        "cada noche desde entonces, y cada noche pasaba lo mismo. La miraba y "
        "pensaba *ah, ese es* — y entonces el nombre no llegaba. Era un hombre. De "
        "mediana edad, o llegando. Pelo oscuro retirándose por delante. Miraba un "
        "poco a la izquierda de quienquiera que lo estuviera soñando, y estaba en "
        "mitad de decir algo, y tenía las cejas levantadas. Estaba mejor pintado que "
        "las otras. Esa era la parte rara. La cocina y el barco y la puerta verde "
        "estaban pintados como se pinta una cosa de memoria: lo importante nítido, "
        "el resto vago. Este tenía un cuello de camisa con un botón de menos en la "
        "punta, y una cicatriz pequeña cruzando una ceja, y ese tipo de detalle que "
        "solo se consigue cuando alguien ha mirado una cara durante años y años y "
        "años. Le preguntó a su tío quién era. Él subió y la miró un rato con las "
        "manos en los bolsillos y dijo que no tenía ni idea, y que él mismo llevaba "
        "preguntándoselo desde 2003 más o menos. Ella hizo lo sensato, y le llevó "
        "tres semanas. Lo dibujó —mal, luego menos mal, luego al cuarto intento lo "
        "bastante bien como para ser reconocible— y llevó el dibujo por el pueblo en "
        "el bolsillo del abrigo y se lo enseñó a la gente. La mujer de la panadería "
        "dijo que no. El hombre de la tienda de bicicletas dijo que no, y luego "
        "sostuvo el dibujo con el brazo estirado y volvió a decir que no, más "
        "despacio. El bibliotecario dijo que se parecía al hermano de alguien, lo "
        "cual no era útil. El padre Costa dijo que se parecía al hermano de todo el "
        "mundo, lo cual era aún menos útil. Un hombre en la parada del autobús dijo "
        "que era un dibujo muy bueno, lo cual ella agradeció pero no pudo usar para "
        "nada. Al cabo de tres semanas se lo había enseñado a treinta y una personas "
        "y ninguna lo conocía. Se sentó en el muro de delante de la farmacia con el "
        "dibujo en la rodilla y lo resolvió, y no disfrutó resolviéndolo. Solo había "
        "dos maneras. O la persona que había dejado caer ese sueño se había mudado "
        "—en cuyo caso la polilla se quedaría en esa viga hasta que la casa se "
        "cayera. O la persona que lo había dejado caer estaba muerta, y el sueño se "
        "había soltado como se suelta lo último de cualquier cosa, y había subido la "
        "cuesta y entrado bajo las tejas y se había plegado contra una viga, y no "
        "quedaba nadie en el mundo a quien dárselo. Se fue a casa y subió la "
        "escalera y se sentó en el borde de la trampilla un buen rato. Su tío subió "
        "al cabo con el té. No preguntó cómo había ido; había deducido claramente "
        "cómo había ido por el hecho de que estuviera sentada a oscuras. —Hay unas "
        "cuatrocientas así —dijo—. Que yo sepa. Las que nadie reclama. No van a "
        "ninguna parte. No se mueren, hasta donde puedo ver: tengo una ahí arriba "
        "con un carro de caballos y no pasa un carro por esta cuesta desde antes de "
        "la guerra. —¿Entonces para qué sirven? —No *sirven* para nada —dijo—. Esa "
        "es la parte que más tardé en entender. Me pasé unos quince años intentando "
        "hacer útil este sitio y no llegué a ninguna parte, porque hacía la pregunta "
        "equivocada. —Señaló con la cabeza hacia las vigas—. No es una oficina de "
        "objetos perdidos. Nadie viene al mostrador. Es solo donde acaban. Ines miró "
        "al hombre de las cejas levantadas, en mitad de decir algo, a alguien que lo "
        "había querido lo bastante como para guardar el botón que faltaba. —Eso es "
        "triste —dijo. —Lo es —convino su tío—. Pero míralo. Alguien quería "
        "muchísimo a ese hombre. Eso sigue siendo verdad. Es verdad ahora mismo, en "
        "esa viga, venga alguien a por ello o no. —Bebió su té—. Hay cosas peores de "
        "las que tener la casa llena."
    ),
    3: (
        "Le llevó casi todo el verano averiguarlo, y averiguarlo no tuvo nada de "
        "mágico. Fue sobre todo hacerle preguntas incómodas a la gente y "
        "equivocarse. Las reglas, hasta donde Ines llegó a establecerlas, eran "
        "estas. Una polilla no iba con cualquiera. Podías llevar una en las manos "
        "ahuecadas hasta una persona y abrir las manos y se quedaba ahí como un "
        "trozo de papel, completamente desinteresada, y al cabo volvía andando por "
        "tu manga. Tenía que ser al anochecer. Ni de noche, ni por la tarde: al "
        "anochecer, esos veinte minutos en que las farolas ya están encendidas pero "
        "todavía ves el color de las cosas. Y tenías que estar cerca de donde la "
        "persona había estado cuando lo perdió. Esa era la parte que lo hacía "
        "difícil, porque significaba averiguar quién, lo que significaba preguntar, "
        "y no hay buena manera de preguntarle a un adulto si ha extraviado "
        "últimamente un sueño sobre un barco. Lo resolvió preguntando por los "
        "cuadros. La mujer de la panadería, cuando Ines le describió un mar gris "
        "visto desde la popa de un barco, dejó de contar el cambio y dijo: —Mi padre "
        "tenía un barco así —y luego—: ¿Por qué? —e Ines dijo que había visto un "
        "cuadro, lo cual era mentira, pero solo una pequeña. Soltó la polilla del "
        "barco delante de la panadería al anochecer de un jueves. Entró por la "
        "ventana de arriba, que estaba abierta por el calor, y no salió. El hombre "
        "que arreglaba bicicletas había perdido el pasillo con la puerta verde. "
        "Estaba casi segura antes de preguntarle y completamente segura después, por "
        "cómo dijo «esa era la casa de mi abuela» y luego dejó de hablar y volvió a "
        "centrar la rueda que estaba centrando. La soltó delante de su tienda a la "
        "tarde siguiente. Él seguía allí, trabajando hasta tarde, y no la vio "
        "hacerlo. Ella miró desde el otro lado de la calle cómo la polilla entraba "
        "por debajo de la persiana. Él salió un minuto después y se quedó en la "
        "acera, mirando a nada en particular, bastante rato. Luego volvió a entrar y "
        "siguió con la rueda. Nunca se lo mencionó a ella, y ella nunca se lo "
        "mencionó a él, y durante un año después le arregló los cables del freno "
        "gratis y ninguno de los dos dijo nunca por qué. Hizo diecinueve aquel "
        "verano. Diecinueve de cientos, y le llevó de junio a mediados de "
        "septiembre, y se equivocó en cuatro y tuvo que traerlas de vuelta. Al final "
        "subió la escalera una última noche antes de que empezara el colegio, "
        "esperando —no sabía bien qué. Alguna mella visible. Algún hueco en las "
        "vigas donde antes había diecinueve. El desván estaba exactamente igual. "
        "—Siempre lo está —dijo su tío, desde la caja—. Eso no es razón para no "
        "hacerlo. Y dejó la luz encendida, como siempre se había dejado encendida, y "
        "bajaron y cerraron la trampilla, y el zumbido siguió muy bajito encima de "
        "ellos toda la noche, como llevaba años, como presumiblemente sigue."
    ),
}

TRANSLATIONS["the-cat-who-walks-you-home"]["es"] = {
    0: (
        "La farola de delante del número cuarenta llevaba apagada desde febrero y el "
        "ayuntamiento tenía un número de expediente para ella. Bruno se sabía el "
        "número de memoria porque su madre lo había dicho por teléfono trece veces, "
        "y cada vez lo había dicho un poco más despacio, y cada vez una persona "
        "distinta le había dicho que estaba registrado. Lo que el número de "
        "expediente significaba, en la práctica, era que los últimos sesenta metros "
        "de la Rua da Cordoaria estaban a oscuras. No daba miedo en octubre. En "
        "octubre bajabas del autobús a las cuatro y media y la luz apenas se estaba "
        "yendo. Para finales de noviembre era de noche de verdad a las cinco y los "
        "sesenta metros se habían convertido en una cosa en la que Bruno pensaba en "
        "el autobús, desde unas tres paradas antes. No había nada allí. Lo sabía. Lo "
        "sabía como se saben las cosas que no cambian nada: había un muro a un lado, "
        "y la parte de atrás del almacén de azulejos al otro, y un portal, y la "
        "esquina. No había nadie allí. Nunca había pasado nada allí. Solo estaba "
        "oscuro, y la oscuridad en la que entras solo a los once años es una "
        "sustancia concreta, más pesada que la otra. Para finales de noviembre había "
        "sacado varias conclusiones sobre aquello. La primera era que correr lo "
        "empeoraba. Lo había intentado la primera semana y había llegado a la "
        "esquina con el corazón disparado y la mochila golpeándole la cadera y la "
        "sensación muy fuerte de haber confirmado algo. Andar era mejor. Andar era "
        "una declaración. La segunda era que el portal era la parte difícil. Estaba "
        "retranqueado casi un metro de la acera, y era el único sitio en los sesenta "
        "metros enteros donde podía haber algo que no vieras hasta estar a su "
        "altura. Había desarrollado, sin haberlo decidido nunca, la costumbre de "
        "andar por la otra acera y girar la cabeza hacia él en el último momento. "
        "Llevaba medio segundo. Lo hizo todas y cada una de las tardes durante "
        "cuatro meses. La tercera cosa era que nada de aquello era razonable, y él "
        "sabía que no era razonable, y saberlo no cambiaba lo más mínimo. Le "
        "gustaría que constara. No era un niño pequeño. Había pasado por aquel "
        "portal de día quizá cuatrocientas veces sin pensar nada. El saber estaba en "
        "un sitio y el andar ocurría en otro, y los dos no se hablaban. Vio al gato "
        "por primera vez un jueves a principios de diciembre. Había doblado la curva "
        "de la farmacia y se había parado, como había empezado a pararse, a hacer el "
        "pequeño asunto privado de decidir andar. Y allí, al fondo, justo en la "
        "esquina donde volvía la luz, había algo sentado. Era gris y era corriente y "
        "estaba mirándolo. Él anduvo. Se quedó. Llegó más o menos a la mitad y se "
        "levantó, sin prisa, y se giró, y dobló la esquina por delante de él —no "
        "marchándose, exactamente, más al paso de alguien que da por hecho que vas "
        "detrás— y cuando él dobló la esquina hacia la luz estaba sentado otra vez, "
        "diez metros más allá, esperando. Dijo: —Hola. Lo miró. Él alargó la mano, "
        "como se hace, e hizo el ruido, y se levantó y se fue pegado al muro y "
        "desapareció entre dos coches aparcados."
    ),
    1: (
        "Lo comentó en el colegio y descubrió, a lo largo de una semana, que aquello "
        "no era un fenómeno nuevo y que cada uno tenía una versión ligeramente "
        "distinta. Inês tenía uno en las escaleras de detrás del mercado. El suyo "
        "era negro y lo llamaba Señor y la había subido las escaleras todas las "
        "noches de enero, cuando su padre trabajaba hasta tarde. Teodoro dijo que el "
        "suyo era naranja y vivía junto al campo de fútbol y solo aparecía cuando "
        "llovía, sobre lo cual tenía una teoría. Las gemelas del curso de arriba "
        "dijeron que ellas no habían visto ningún gato pero que su madre sí, de "
        "pequeña, en la carretera que va a la cantera, y que en su versión había "
        "salido de debajo de un coche y la había acompañado todo el camino hasta el "
        "cruce y ya no estaba cuando ella se giró. La única regla que estaba en "
        "todas las versiones, y Bruno lo comprobó, era esta: nunca venía cuando lo "
        "llamabas. Reunió doce relatos para finales de enero y los escribió al final "
        "del cuaderno de portugués, bajo un título que luego tachó porque parecía "
        "infantil. Gris, negro, naranja, atigrado, y uno sobre el que Rita no daba "
        "su brazo a torcer: blanco, con la cara gris. Calles distintas. Años "
        "distintos. El de la madre de las gemelas era de 1994 más o menos, lo que lo "
        "hacía o un gato muy viejo o, como observó Teodoro a considerable volumen en "
        "el pasillo, no un gato. Nadie había tocado ninguno. Lo comprobó "
        "específicamente, porque él había alargado la mano la primera noche y se "
        "había sentido tonto durante una semana después. Nadie lo había hecho. "
        "Llegaban a unos dos metros y se quedaban a dos metros y desaparecían en "
        "cuanto estabas en la luz. Nadie había visto llegar a ninguno, tampoco. Eso "
        "tardó más en notarlo, porque una ausencia es difícil de notar. En los doce "
        "relatos el gato simplemente ya estaba allí, sentado, al fondo, mirándote. "
        "No viniendo andando. No saliendo de debajo de nada. Sentado, en el sitio "
        "donde acababa la oscuridad, ya mirándote antes de que tú lo miraras. Podías "
        "quedarte en lo alto de la calle a las ocho de la tarde cuando estabas "
        "perfectamente bien y decir *ven, ven, ven* hasta sentirte ridículo, y no "
        "pasaba nada. Teodoro lo había intentado con comida. Inês lo había intentado "
        "una semana seguida en febrero por pura curiosidad científica y no consiguió "
        "más que un resfriado. Y entonces una noche en que estabas asustado, estaba "
        "allí. La abuela de Bruno, que fue la única adulta a la que se lo contó, "
        "escuchó hasta el final con las manos en el fregadero y luego dijo algo que "
        "él no entendió hasta unos cuatro años después. Dijo: —No es el gato el que "
        "cambia. Él le preguntó qué se suponía que significaba eso. Ella secó un "
        "vaso y lo puso en el escurridor y no contestó durante el tiempo suficiente "
        "como para que él supusiera que no iba a hacerlo. —Cuando yo era niña —dijo—, "
        "había una mujer en esta calle que no podía salir de noche en absoluto. No "
        "que no quisiera: no podía. Algo le había pasado, antes, en otro sitio, y "
        "nadie en la calle lo supo nunca, y no era asunto nuestro. Y durante unos "
        "veinte años, siempre que tenía que ir a algún sitio de noche, uno de los "
        "hombres daba la casualidad de que estaba en lo alto de las escaleras "
        "fumando un cigarro. Hombres distintos. Nunca el mismo dos veces seguidas. "
        "Nunca acordado, hasta donde yo pude ver. —No es lo mismo. —No —convino su "
        "abuela—. No lo es. Y le dio el paño para secar, que era como acababan las "
        "conversaciones en aquella cocina."
    ),
    2: (
        "En marzo los días se alargaron y los sesenta metros volvieron a ser sesenta "
        "metros. Bruno lo notó solo como se nota que a uno le ha dejado de doler una "
        "muela, es decir, tarde, y por accidente. Subía del autobús un martes y "
        "estaba pensando en algo que había pasado en mates, y dobló la curva de la "
        "farmacia y no se paró. Estaba casi al final cuando se dio cuenta de que no "
        "había mirado a la esquina. Se paró entonces, en mitad de la parte oscura, y "
        "se giró, y miró bien de dónde venía y adónde iba, y no había nada en "
        "ninguna de las dos direcciones. El almacén de azulejos. El muro. El portal. "
        "Los contenedores. El gato no estaba. Se quedó allí un rato, y se sintió —y "
        "nunca ha conseguido que esto suene sensato— un poco rechazado. Volvió a la "
        "noche siguiente a propósito. Bajó por el medio de la calle despacio, "
        "mirando cada parte por turno: el muro, la parte de atrás del almacén, los "
        "contenedores, el portal. Se metió en el portal un minuto entero, cosa que "
        "no había hecho nunca en su vida, y descubrió que era un portal con un "
        "escalón gastado y unas hojas en la esquina y un cerrojo pintado encima unas "
        "nueve veces. Dijo *ven*, dos veces, en voz baja, sintiéndose ridículo. "
        "Había un coche en algún sitio de la avenida, y la televisión de alguien a "
        "través de una ventana, y ese era el contenido entero de la Rua da Cordoaria "
        "a las seis y diez de un miércoles de marzo. Lo intentó otra vez en abril, "
        "con un trozo de chorizo, de lo que todavía se avergüenza. Le dijo a la "
        "calle vacía: —Sigo aquí, ¿sabes? No pasó nada, que es lo que pasa. Se fue a "
        "casa y cenó y no lo mencionó, y le llevó hasta abril más o menos entender "
        "que el gato no había dejado de venir. Él había dejado de necesitarlo. Eran "
        "dos acontecimientos completamente distintos que habían parecido, desde "
        "dentro, el mismo."
    ),
    3: (
        "El invierno siguiente la luz de delante del número cuarenta seguía apagada y "
        "había un número de expediente nuevo. Bruno tenía doce años para entonces y "
        "había dejado de pensar en los sesenta metros por completo, y la razón por la "
        "que recuerda algo de todo esto es una niña llamada Cátia que se mudó a los "
        "pisos de encima de la farmacia en octubre y que tenía nueve años. Se fijó "
        "en ella porque se paró. Dobló la curva una tarde a eso de las cinco y media "
        "y había una persona pequeña de pie en lo alto de la parte oscura con la "
        "mochila apretada contra el pecho con los dos brazos, haciendo el asunto "
        "privado de decidir, y no decidiendo. Él sabía exactamente lo que estaba "
        "haciendo. Lo había hecho durante cuatro meses. No dijo nada al respecto, "
        "porque tenía doce años y sabía que sería lo incorrecto. Pasó a su lado y "
        "dijo «boa noite» y siguió a velocidad normal, y ella fue detrás de él, unos "
        "cuatro metros atrás, todo el camino hasta doblar la esquina hacia la luz. "
        "Lo hizo todas las tardes durante unas tres semanas, a cuatro metros, y "
        "ninguno de los dos lo mencionó nunca. Y entonces una tarde a principios de "
        "diciembre él llegaba tarde —se había quedado al fútbol y había cogido el "
        "autobús siguiente— y dobló la curva casi a las siete, y la parte oscura "
        "estaba oscura de verdad, y no había nadie en ella. Y al fondo, en la "
        "esquina donde volvía la luz, algo gris estaba sentado mirándolo. Bruno se "
        "paró. Se quedó allí en lo alto de la Rua da Cordoaria un rato, bastante más "
        "del que necesitaba, mirando sesenta metros de oscuridad hacia un gato que "
        "no veía desde hacía año y medio. Entonces anduvo. Se levantó cuando él "
        "estaba a la mitad, sin prisa, y dobló la esquina por delante al paso de "
        "algo que da por hecho que vas detrás, y cuando él entró en la luz estaba "
        "sentado diez metros más allá. Esta vez no alargó la mano. Había aprendido "
        "eso al menos. Dijo: —Ya lo sé. Ya voy. Y lo miró, y se levantó, y se fue "
        "pegado al muro y desapareció entre dos coches aparcados. Se lo contó a su "
        "abuela aquella noche, porque seguía siendo la única adulta a la que se lo "
        "contaba, y ella estaba haciendo lo mismo en el mismo fregadero. —Ha vuelto "
        "—dijo—. Tengo doce años. —Mm —dijo su abuela. —Pero no tenía miedo. "
        "Llegaba tarde, eso es todo. Solo llegaba tarde. Su abuela cerró el grifo y "
        "se secó las manos y lo miró un momento con una expresión que él no supo "
        "leer en absoluto. —Bruno —dijo—. Estabas solo, a oscuras, y tienes doce "
        "años, y te quedaste en lo alto de esa calle un minuto entero antes de "
        "moverte. Te vi desde la ventana. —Colgó el paño en la barra—. No es el gato "
        "el que cambia."
    ),
}


# ═══════════════════════════════════════════════════════════════════════

def main() -> None:
    catalog = json.loads(CATALOG.read_text())
    strings = catalog["strings"]
    added = 0

    for story_id, by_lang in TRANSLATIONS.items():
        story = json.loads((STORIES / f"{story_id}.json").read_text())
        chapters = {c["index"]: c["text"] for c in story["chapters"]}

        # Collect per-chapter so one entry can carry several languages.
        per_chapter: dict[int, dict[str, str]] = {}
        for lang, by_index in by_lang.items():
            for idx, text in by_index.items():
                per_chapter.setdefault(idx, {})[lang] = text

        for idx, langs in sorted(per_chapter.items()):
            key = chapters.get(idx)
            if key is None:
                print(f"  !! {story_id} has no chapter {idx}")
                continue

            entry = strings.get(key, {"extractionState": "manual",
                                      "localizations": {}})
            locs = entry.setdefault("localizations", {})
            locs["en"] = {"stringUnit": {"state": "translated", "value": key}}
            for lang, value in langs.items():
                locs[lang] = {"stringUnit": {"state": "translated",
                                             "value": value}}
            strings[key] = entry
            added += 1
            print(f"  {story_id} ch{idx}: {', '.join(sorted(langs))}")

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False))
    print(f"\n{added} chapter bodies merged; catalog now {len(strings)} keys")


if __name__ == "__main__":
    main()
